### ISSUE TITLE
BD Oracle

### ISSUE THREAD

**Issue by ElyssonRaphaeL** [SIMITGROUP/phpjasperxml#10]
I could not connect to BD oracle in your project!
Can you help me?

**Comment by kstan79** [comment]
you may use pdo, u can refer sample code from readme again.

**Comment by ElyssonRaphaeL** [comment]
Eu uso pdo e apresenta a mensagem abaixo:
Fail to connect database

**Comment by ElyssonRaphaeL** [comment]
I use pdo and it displays the message below:
Fail to connect database

** The connection data is correct!

**Comment by kstan79** [comment]
Hi sorry, PDO method u shall submit last parameter according below:
if you wish to use oracle, can use oci instead
```
$this->myconn = new PDO ($cndriver.":host=$db_host;dbname=$dbname",$db_user,$db_pass);
```

**Comment by kstan79** [comment]
since no reply for long time, i assume solve?
