### ISSUE TITLE
how to passing parameter from master report to sub report? i try passing but not showing

### ISSUE THREAD

**Issue by anggadedysaputro** [SIMITGROUP/phpjasperxml#100]
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/743c778c-cad3-4b5a-a9c1-7b5abbcc084d)

![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/91595dd8-e23c-4280-855b-10dfab3af79b)

![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/db3c0107-b7e9-41f0-a308-7a7a1225167c)

![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/be99c693-20ef-46c5-bfbb-77840de07a04)

![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/effe9830-9994-4d7f-b6cc-83702d489328)

**Comment by kstan79** [comment]
sorry previously busy, will look into it

**Comment by kstan79** [comment]
try 2.1.10, it should work now.

**Comment by kstan79** [comment]
2.1.11 instead

**Comment by anggadedysaputro** [comment]
okeey,, thank you so much mr @kstan79 , i will try again
