### ISSUE TITLE
help,, how solve number converted in scientific notation after export excel?

### ISSUE THREAD

**Issue by anggadedysaputro** [SIMITGROUP/phpjasperxml#102]
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/19a8dbba-9068-48cd-81cc-c47078a6b19f)

**Comment by kstan79** [comment]
hm.. i not so sure does the numbering format can carry into export excel. have you define numbering format?

**Comment by anggadedysaputro** [comment]
no mr @kstan79

**Comment by kstan79** [comment]
Then try set it
