### ISSUE TITLE
can i create multiple sheet in export excel ?

### ISSUE THREAD

**Issue by anggadedysaputro** [SIMITGROUP/phpjasperxml#103]

**Comment by kstan79** [comment]
At the moment no, I'm wondering why you need it.

**Comment by anggadedysaputro** [comment]
to separate master data and reports mr @kstan79

**Comment by kstan79** [comment]
there is no plan for complicated use case, the goal of this project is help developer align pdf report. IMHO fancy reporting function shall do outside jasper report, it is kind of old way to present report. use rich frontend approach is the future
