### ISSUE TITLE
passing parameter in postgresql database not working in localhost, in jasper studio and mysql database working properly

### ISSUE THREAD

**Issue by anggadedysaputro** [SIMITGROUP/phpjasperxml#104]
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/1dcd1df5-ee2c-43c0-aa14-290e217b4437)
error in localhost
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/44c9e6ee-8ddc-49dd-bcf1-b2df4384bd51)
query from jasper studio

**Comment by kstan79** [comment]
nice try, will explore it

**Comment by anggadedysaputro** [comment]
solved mr @kstan79, it turns out that the order of the method chain matters, the setDataSource method should come first, then the setparameter method
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/2d510203-998c-420b-b0e8-70cb5b05696b)
