### ISSUE TITLE
how to passing text parameter to postgresql function? i found an error 

### ISSUE THREAD

**Issue by anggadedysaputro** [SIMITGROUP/phpjasperxml#108]
an integer type is normal but text type error

![gambar](https://github.com/user-attachments/assets/4fe0c9e5-e68d-47ce-9b2b-4e7c150be148)
![gambar](https://github.com/user-attachments/assets/53e96d27-9a7f-4a06-99d0-b07902ac5ac4)

**Comment by kstan79** [comment]
in jasperstudio, field/variable/parameter with type string will auto quite by `"`, that cause this issue. it is design and you shall define as another data type like you mentioned integer

**Comment by anggadedysaputro** [comment]
so I have to change the type to integer mr @kstan79 ?
i try change to integer but error eval failed like this
![gambar](https://github.com/user-attachments/assets/f0f2a328-767a-471a-8442-78837cce71f9)

I still can't understand what you mean, Mr. Kstan

**Comment by kstan79** [comment]
hm.. sorry seems like you wish to pass string as parameter into the database function. due to it encodeed `"=>&quote` become error.
there is work arround which u try add `"` or `'` in between `$P{xkategory}` see is it helpful?

**Comment by anggadedysaputro** [comment]
no mr @kstan79 it still error

**Comment by kstan79** [comment]
There is 2 work around which is
1. you prepare sql at php level and override sql when you call the library. In that case you hardcode sql in jrxml like `select "a" as field1, 1 as field2 from dual` so jasperstudio can obtain the field

2. You can run sql outside and obtain the array of data, then pass into report for render the pdf. You can refer examples and wiki

**Comment by anggadedysaputro** [comment]
ok thanks mr @kstan79
