### ISSUE TITLE
textfield in detail band cannot strecth to max height, how to solve this ?

### ISSUE THREAD

**Issue by anggadedysaputro** [SIMITGROUP/phpjasperxml#109]
![gambar](https://github.com/user-attachments/assets/9881a440-15f1-4d49-acaf-e577834c1b41)

**Comment by kstan79** [comment]
There is option stretch text in properties

**Comment by anggadedysaputro** [comment]
![gambar](https://github.com/user-attachments/assets/5060fb20-f9d6-4654-971d-78ff6d1ec024)

in text adjust ?

**Comment by kstan79** [comment]
I think Stretch height is correct, but I wondering why cause this. I no face this issue before

**Comment by anggadedysaputro** [comment]
do you have any suggestions mr @kstan79 ?

**Comment by kstan79** [comment]
I mean this problem should not exists. You may check band setting too?

**Comment by anggadedysaputro** [comment]
simple example test in jasper studio
![gambar](https://github.com/user-attachments/assets/1faf9ced-010f-4ca4-9fd3-ea24b794adf7)
test in localhost
![gambar](https://github.com/user-attachments/assets/9b7fddf0-0ac1-48bb-a459-91b70fa47445)
this is my file jrxml code -> [new 2.txt](https://github.com/user-attachments/files/17266420/new.2.txt)

**Comment by kstan79** [comment]
Set text align top

**Comment by anggadedysaputro** [comment]
work correctly mr @kstan79, but the final result of height in each textfield not same
![gambar](https://github.com/user-attachments/assets/94296d36-b3e9-4370-8f4e-b3d438603f0d)

**Comment by kstan79** [comment]
Yes, so you should not use text bolder in this case. Try draw a line start from x0, y0 to xend at detail band. It give you similar look

**Comment by anggadedysaputro** [comment]
i try to add line from basic element tool bar not working mr @kstan79 
![gambar](https://github.com/user-attachments/assets/c030535d-d0e9-48b9-ab5a-678dae59642c)

**Comment by kstan79** [comment]
add top only, dont add bottom. no point

**Comment by anggadedysaputro** [comment]
the horizontal line is working if use top only, but not symetric line,, then the vertical line not stretch to tallest height of textfield

![gambar](https://github.com/user-attachments/assets/1cebb803-5d04-4de9-bbe9-3146f50b4e5e)

**Comment by kstan79** [comment]
Use background band

**Comment by anggadedysaputro** [comment]
not working mr @kstan79

**Comment by kstan79** [comment]
usually design format will put total at last page footer, and you use background to draw a rectangle + vertical line for break column. refer examples

**Comment by anggadedysaputro** [comment]
still not working, is there something wrong?
![gambar](https://github.com/user-attachments/assets/3c68e601-bc6d-4449-b47f-6e7e119af40f)
![gambar](https://github.com/user-attachments/assets/9c56ac88-2255-4b3a-8f63-a4b004cc0eed)

**Comment by kstan79** [comment]
you need to think how to draw background table via background band. Continue Try yourself

**Comment by anggadedysaputro** [comment]
i does'nt understand mr @kstan79, may I ask for an example of a jrxml file?

**Comment by kstan79** [comment]
below is example of detail band, make it full height and draw vertical line

<img width="795" alt="Screenshot 2024-10-07 at 3 02 10 PM" src="https://github.com/user-attachments/assets/7e15c877-de4e-45fe-a751-c42caf6fd964">

**Comment by kstan79** [comment]
It is not supported, I did some research before but it can't solve when content go multiple pages.

**Comment by anggadedysaputro** [comment]
ok thank you mr @kstan79
