### ISSUE TITLE
error in PHPJasperXML

### ISSUE THREAD

**Issue by Mayco-Andrey-Ranghetti** [SIMITGROUP/phpjasperxml#12]
Hi.
I am trying to use PHPJasperXML on PDO Connection, and I have a lot of errors.
What am I doing wrong?
![capture](https://user-images.githubusercontent.com/33654096/32772750-fcedda7a-c90d-11e7-8037-8b302ad71223.PNG)

**Comment by Mayco-Andrey-Ranghetti** [comment]
Hi,
I saw in other issue the answer for my question. I disabled the errors in php.ini and I have success.

**Comment by kstan79** [comment]
Yes, you may found [get solution here](https://github.com/SIMITGROUP/phpjasperxml/issues/8)
