### ISSUE TITLE
phpjasperxml XML source instead DB

### ISSUE THREAD

**Issue by harvy76** [SIMITGROUP/phpjasperxml#14]
Hello,
I would like to ask you, if it is possible use this project for print documents from XML source instead of DB.

Please, can you try to write me, how can I do it? do you have some example, please?

Thank you
Jan Havranek

**Comment by kstan79** [comment]
At the moment it is not supported. You can either:
1. add new connection method, modify connect(),transferDBtoArray(), test it properly and send pull request. Or
2. 'hack' by override the variable after function 'transferDBtoArray()'. you can override variable '$this->arraysqltable' and '$this->m'. 
`
$PHPJasperXML = new PHPJasperXML("en","TCPDF");
$PHPJasperXML->arrayParameter =array();
$PHPJasperXML->load_xml_file($templatefile);
$PHPJasperXML->sql = $sql;  //if u wish to override the sql
$PHPJasperXML->transferDBtoArray(DBSERVER,DBUSER,DBPASS,DBNAME);
$data=getManyRowOfRecordsHere();
$PHPJasperXML->arraysqltable=$data
$PHPJasperXML->m=count($data);
$PHPJasperXML->outpage('I');
`

Hope this help

**Comment by kstan79** [comment]
$data=getManyRowOfRecordsHere();

$PHPJasperXML = new PHPJasperXML("en","TCPDF");
$PHPJasperXML->arrayParameter =array();
$PHPJasperXML->load_xml_file($templatefile);
$PHPJasperXML->sql = $sql;  //if u wish to override the sql
$PHPJasperXML->transferDBtoArray(DBSERVER,DBUSER,DBPASS,DBNAME);
$PHPJasperXML->setData($data);
$PHPJasperXML->outpage('I');


You may try it

**Comment by kstan79** [comment]
no more reply, then we close this issue
