### ISSUE TITLE
SubReport 0.8 work but v1.0 doesn't work

### ISSUE THREAD

**Issue by Marivint** [SIMITGROUP/phpjasperxml#16]
Using PHPJasperXML-1.0.inc.php

SubReport is displayed when i use v0.8 PHPJasperXMLSubReport.inc.php (with PHP 5.6 or PHP 7) and does not display with the latest v1.0 PHPJasperXMLSubReport.inc.php.

Did something change on SubReport path ?

$P{SUBREPORT_DIR} + "mysubreport.jasper"

With SUBREPORT_DIR =  folder/

= folder/mysubreport.jasper

My SubReport :

![facture](https://user-images.githubusercontent.com/22272618/38252067-7aa1ff56-3753-11e8-9982-dd093b2082a3.JPG)

**Comment by kstan79** [comment]
You need to use .jrxml instead. .jasper file is binary cannot use by php.

**Comment by kstan79** [comment]
no reply since so longtime, i think issue solved
