### ISSUE TITLE
Undefined property: PHPJasperXML::$footerbandheight

### ISSUE THREAD

**Issue by acer22969** [SIMITGROUP/phpjasperxml#17]
I'm use php7.2 +laravel5.6 +MSSQL+phpjasper-laravel(from geekcom)+jaspersoft
Here is my part of code in laravel Controller : 
```
$server = "localhost";
$user="test123";
$pass = "test123";
$db = "test";

$PHPJasperXML = new PHPJasperXML("en","TCPDF");
$PHPJasperXML->arrayParameter=array('para1'=>'1','para2'=>'2');
$PHPJasperXML->load_xml_file(app_path().'/lib/PHPJasperXML/sample1.jrxml');
$dbdriver="sqlsrv";
$PHPJasperXML->transferDBtoArray($server,$user,$pass,$db,$dbdriver);
$PHPJasperXML->outpage('I'); 
```
Here is the error i get in laravel  : 
![image](https://user-images.githubusercontent.com/25860075/43369551-25f879ce-93a3-11e8-8fb2-c69cb596c1b9.png)

Please teach me how to fix this kind of error
Thank you very much!

**Comment by kstan79** [comment]
hi, seems php7.2 required to declare every attribute in the class. What you can do is declare all vairable in the class:

`private $footerbandheight=0;`

**Comment by acer22969** [comment]
It's work!! 
Thanks for your answer.

**Comment by kstan79** [comment]
You may send pull request if you test it work perfectly.
