### ISSUE TITLE
Last Page Footer not working correctly

### ISSUE THREAD

**Issue by sanojsilva** [SIMITGROUP/phpjasperxml#18]
Hi,
I'm using this for over an year now and its great but there is one major problem i need to overcome. When i put content in the last page footer band it prints on every page not just on the last page. How do i avoid that.
very much needed.
Thanks.

**Comment by kstan79** [comment]
Hi Sanojsilva, if I'm not wrong, u have to create both footer and last page footer. Else it may have strange behaviour. Sorry of bad

**Comment by sanojsilva** [comment]
Hey @kstan79 ,
Thank You very much that worked
