### ISSUE TITLE
fatal error 

### ISSUE THREAD

**Issue by jpramanuj** [SIMITGROUP/phpjasperxml#19]
please help me to solve it.......

Fatal error: Uncaught ArgumentCountError: Too few arguments to function PHPJasperXML::analyse_expression(), 1 passed in C:\xampp\htdocs\Jinaltech\class\PHPJasperXML-0.9d.inc.php on line 597 and exactly 3 expected in C:\xampp\htdocs\Jinaltech\class\PHPJasperXML-0.9d.inc.php:5439 Stack trace: #0 C:\xampp\htdocs\Jinaltech\class\PHPJasperXML-0.9d.inc.php(597): PHPJasperXML->analyse_expression(Object(SimpleXMLElement)) #1 C:\xampp\htdocs\Jinaltech\class\PHPJasperXML-0.9d.inc.php(442): PHPJasperXML->element_staticText(Object(SimpleXMLElement)) #2 C:\xampp\htdocs\Jinaltech\class\PHPJasperXML-0.9d.inc.php(259): PHPJasperXML->default_handler(Object(SimpleXMLElement)) #3 C:\xampp\htdocs\Jinaltech\class\PHPJasperXML-0.9d.inc.php(166): PHPJasperXML->xml_dismantle(Object(SimpleXMLElement)) #4 C:\xampp\htdocs\Jinaltech\class\PHPJasperXML-0.9d.inc.php(171): PHPJasperXML->load_xml_string('<?xml version="...') #5 C:\xampp\htdocs\Jinaltech\index.php(30): PHPJasperXML->load_xml_file('123.jrxml') #6 {main} thrown in C:\xampp\htdocs\Jinaltech\class\PHPJasperXML-0.9d.inc.php on line 5439

**Comment by jpramanuj** [comment]
I try both of this version in php 7.2.9 but not getting success..

**Comment by jpramanuj** [comment]
there is a blank screen while i use version 1.0

**Comment by kstan79** [comment]
this issue same with #20, mean it not yet support php 7.1 and above. Any follow up please use that thread.
