### ISSUE TITLE
Driver sqlsrv support

### ISSUE THREAD

**Issue by ajsb85** [SIMITGROUP/phpjasperxml#2]

**Comment by alexsalas** [comment]
HI @kstan79 What's about this issue?

**Comment by kstan79** [comment]
Hi @ajsb85 we very seldom use github. We'd update our latest code into github by right there is alot of changes. We will reject your pull request at the moment cause we worry it crash. if you tested latest version and find it working well can resubmit PR. 

thanks of using PHPjasperXML and sorry of we can't provide support of it.
