### ISSUE TITLE
not working getting error. using XAMPP for Windows 7.1.17 PHP Version 7.1.17

### ISSUE THREAD

**Issue by kiranugale** [SIMITGROUP/phpjasperxml#20]
Notice: Undefined property: PHPJasperXML::$footerbandheight in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 262

Notice: Undefined property: PHPJasperXML::$columnfooterbandheight in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 262

Notice: Undefined property: PHPJasperXML::$footerbandheight in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 262

Notice: Undefined property: PHPJasperXML::$columnfooterbandheight in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 262

Notice: Undefined property: PHPJasperXML::$footerbandheight in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 262

Notice: Undefined property: PHPJasperXML::$columnfooterbandheight in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 262

Notice: Undefined variable: linewidth in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 1096

Notice: Undefined variable: dash in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 1133

Notice: Undefined variable: linewidth in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 1096

Notice: Undefined variable: dash in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 1133

Notice: Undefined variable: linewidth in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 1096

Notice: Undefined variable: dash in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 1133

Notice: Undefined property: PHPJasperXML::$footerbandheight in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 262

Notice: Undefined property: PHPJasperXML::$columnfooterbandheight in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 262

Fatal error: Uncaught ArgumentCountError: Too few arguments to function PHPJasperXML::analyse_expression(), 1 passed in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 595 and exactly 3 expected in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php:5511 Stack trace: #0 C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php(595): PHPJasperXML->analyse_expression(Object(SimpleXMLElement)) #1 C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php(440): PHPJasperXML->element_staticText(Object(SimpleXMLElement)) #2 C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php(258): PHPJasperXML->default_handler(Object(SimpleXMLElement)) #3 C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php(166): PHPJasperXML->xml_dismantle(Object(SimpleXMLElement)) #4 C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php(171): PHPJasperXML->load_xml_strin in C:\xampp\htdocs\phpjasperxml-master\PHPJasperXML\class\PHPJasperXML-1.0.inc.php on line 5511 @ @kstan79 
![image](https://user-images.githubusercontent.com/19143501/45996452-d9c74c80-c0b9-11e8-8105-b86ca89be38b.png)

**Comment by kstan79** [comment]
hi, at the moment php7.1 and above required default value to all parameter in function (if not supply all parameter from caller), else will come out similar error.

At the mean time we focus development in php 7.0, coming soon we will port into php7.2.
you can switch to php7.0 at the mean time.

**Comment by kiranugale** [comment]
hi thanks for the help but in php 7.0 having issue thatwhy i switched on 7.1
i will wait for port.

**Comment by kstan79** [comment]
ok, we will work on it within a month.

**Comment by kiranugale** [comment]
Thank you. I appreciate your work. God Bless you.

**Comment by kstan79** [comment]
structure overhaul, u may try with new structure. Im using it in our existing project with php 7.2. so far so good. There is big changes in folder structure, hope it not effect much in your structure.

**Comment by kstan79** [comment]
i recommend you to use phpjasperxml as your project submodule

**Comment by kstan79** [comment]
refer latest readme as example

**Comment by kiranugale** [comment]
Kstan79 I thank you from the bottom of my heart. your new code is working properly.
I don't have anything to give you but I would like to share my project with you.
it's Visitor Management system. please share your email id I will share with you.
this is my email id keeranugale@gmail.com.
once again thank you.....

**Comment by kstan79** [comment]
You’re welcome. This is open source project, we live in same world, we help each other’s.
