### ISSUE TITLE
Indirect modification of overloaded element of SimpleXMLElement has no effect

### ISSUE THREAD

**Issue by lvsan** [SIMITGROUP/phpjasperxml#21]
Hi I have the below error when try to print the report from php.

[yii\base\ErrorException:8] exception 'yii\base\ErrorException' with message 'Indirect modification of overloaded element of SimpleXMLElement has no effect' in D:\wamp64\www\master\reports\class\PHPJasperXML-1.0.inc.php:388

below is the line that causing the error :

$this->pointer=&$this->arraygroup[$xml_path["name"]]["groupHeader"];

Can anyone help me or advise on this how to solve it?

Thanks.

Regards,
lvsan

**Comment by kstan79** [comment]
it look weird and I never see this before, you use group header? and how you group the data?

**Comment by kstan79** [comment]
Seems there is no additional comment I will close this topic.
