### ISSUE TITLE
problem with generate pdf

### ISSUE THREAD

**Issue by disney8** [SIMITGROUP/phpjasperxml#23]
Illegal offset type in C:\xampp\htdocs\phpjasperxml-master\version\1.1\abstractPHPJasperXML.inc.php on line 589
A non-numeric value encountered in C:\xampp\htdocs\phpjasperxml-master\tcpdf\tcpdf.php on line 7324
TCPDF ERROR: Some data has already been output, can't send PDF file

**Comment by kstan79** [comment]
it seems is error reporting cause it draw at html content, i'd disable error report. update your code and try again.

**Comment by disney8** [comment]
Thanks, it's perfect :)
