### ISSUE TITLE
error connecting to postgresql

### ISSUE THREAD

**Issue by jschussmuller** [SIMITGROUP/phpjasperxml#26]
Hi! I have a problem while I try to connect to postgresql:
![image](https://user-images.githubusercontent.com/14302068/47649022-a2d1d400-db5a-11e8-9259-6dd843e421ab.png)

the php file looks like this:

<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

include_once("../PHPJasperXML.inc.php");
include_once ('setting.php');
error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE)

$PHPJasperXML = new PHPJasperXML();
//$PHPJasperXML->debugsql=true;
$PHPJasperXML->arrayParameter=array("parameter1"=>1);
$PHPJasperXML->load_xml_file("Doctores.jrxml");

//$PHPJasperXML->transferDBtoArray($server,$user,$pass,$db); //* use this line if you want to connect with mysql

//if you want to use universal odbc connection, please create a dsn connection in odbc first
//$PHPJasperXML->transferDBtoArray($server,"odbcuser","odbcpass","phpjasperxml","odbc"); //odbc = connect to odbc
$PHPJasperXML->transferDBtoArray($server,"postgres","postgres","clinica","psql"); //odbc = connect to potgresql
$PHPJasperXML->outpage("I");    //page output method I:standard output  D:Download file

what I am doing wrong?

**Comment by jschussmuller** [comment]
now, after enable the postgres connections from php.ini I got new error:
Fail to connect database

**Comment by kstan79** [comment]
Ya ya, i notice the variable name wrong, and the sample sql in jrxml come with symbol '`', which is not compatible with postgresql. After update you may try run example8 (you required to configure postgresql user/password/host/dbname too)

**Comment by jschussmuller** [comment]
Hi kstan79! got the same issue, my sample8.php looks like this:

`<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

include_once("../PHPJasperXML.inc.php");
include_once ('setting.php');





$PHPJasperXML = new PHPJasperXML();
//$PHPJasperXML->debugsql=false;
$PHPJasperXML->arrayParameter=array("parameter1"=>1);
$PHPJasperXML->load_xml_file("report3.jrxml");
$PHPJasperXML->transferDBtoArray("localhost","postgres","postgres","clinica");

$PHPJasperXML->outpage("I");    //page output method I:standard output  D:Download file


?>
`
I got it working in mysql without problems, but I don't want to change the database of my project.

**Comment by kstan79** [comment]
You need to defined 5th parameter ‘psql’. Please check original example8 once again.

**Comment by jschussmuller** [comment]
I tried like that as well:
`<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

include_once("../PHPJasperXML.inc.php");
include_once ('setting.php');





$PHPJasperXML = new PHPJasperXML();
//$PHPJasperXML->debugsql=false;
$PHPJasperXML->arrayParameter=array("parameter1"=>1);
$PHPJasperXML->load_xml_file("report3POSTGRE.jrxml");
$pgport = 5432;

$PHPJasperXML->transferDBtoArray("localhost","postgres","postgres","clinica","psql");

$PHPJasperXML->outpage("I");    //page output method I:standard output  D:Download file


?>
`
and still getting the same error, of course the database does work and the connections are fine.

thanks for your answers!

**Comment by kstan79** [comment]
Try set debugsql=true, then try run the sql in phppgadmin?
`$PHPJasperXML->debugsql=true;`

**Comment by kstan79** [comment]
Issue still exists? If no issue then close ticket
