### ISSUE TITLE
Print With Expression Not Working

### ISSUE THREAD

**Issue by hidayat88** [SIMITGROUP/phpjasperxml#27]
Hi, I'm trying to hide and view an image using "Print With Expression" using this expression called from database `$F{students_1a}.contentEquals( "Yes" )`, but not working. Inside Ireport it is working well.

![image](https://user-images.githubusercontent.com/15993755/48390431-f6d4df00-e73c-11e8-9328-27e304fd6111.png)
Image 1: Expression declared inside Ireport

![image](https://user-images.githubusercontent.com/15993755/48390456-1a982500-e73d-11e8-89b8-4060b40d90eb.png)
Image 2: using Ireport directly the another image hidden and another one showed.

![image](https://user-images.githubusercontent.com/15993755/48390537-7bbff880-e73d-11e8-95ab-dc8d602b0261.png)
image 3: PDF generated didnt hide the 'X' image.

**Comment by kstan79** [comment]
hi, 
We not use java, and php dont know the syntax. you shall use syntax as below code:
```
$F{student_1a}=="Yes"
```

**Comment by hidayat88** [comment]
> hi,
> We not use java, and php dont know the syntax. you shall use syntax as below code:
> 
> ```
> $F{student_1a}=="Yes"
> ```

Hi, I already using that expression, it works with ireport, but not with phpjasperxml. Another one issue, the date format also cannot use some custom format, only standard date and time works.

**Comment by kstan79** [comment]
Try 
```
“$F{student_1a}” == “Yes” 
```


Supported date format you may try open abstractPHPJasperxml.inc.php and find keyword ‘##’. Check your format is it defined inside

**Comment by hidayat88** [comment]
I already check that the script is working only for line type. Once using this '$F{students_1a}=="Yes"'
Other types such as image, square, text, eclipse, are not hidden once the condition other that stated.

**Comment by hidayat88** [comment]
Maybe I can try & error by modifying the source code to support the image hidden, by adding some attributes and expressions just need to go through the tcpdf documentation.

**Comment by kstan79** [comment]
hi,
i'd check seems it is missing features. you can edit 'PHPJasperXMLElement.inc.php', find keyword 'printWhenExpression'. 'element_Image' seems missing the attribute.

**Comment by kstan79** [comment]
i'd approved the PR, please verify that. if work well you may close this issue.

**Comment by hidayat88** [comment]
Thanks. It works well. I'd changed the database content into "No"
![image](https://user-images.githubusercontent.com/15993755/48520514-d5decc00-e8ab-11e8-8e9b-8974a8a54b29.png)
Image 1:  Database content changed to "No" condition.

![image](https://user-images.githubusercontent.com/15993755/48520548-fc046c00-e8ab-11e8-8906-65e9c63090fc.png)
Image 2: The generate report shows "X" the jpg image and hide the "/" image.

Next I changed the database to "Yes"
![image](https://user-images.githubusercontent.com/15993755/48520668-6fa67900-e8ac-11e8-835c-04039600d4bd.png)
Image 3: Database content changed to "Yes" condition.

![image](https://user-images.githubusercontent.com/15993755/48520733-aa101600-e8ac-11e8-842f-9f6a30cef97d.png)
Image 4: The generate report shows "/" the jpg image and hide the "X" image.

That's all. Thanks.
