### ISSUE TITLE
Differences between Jasper Report Preview and produced PDF

### ISSUE THREAD

**Issue by toothlesstiger** [SIMITGROUP/phpjasperxml#29]
using some groovy operators inside the report seems to hide the pdf output, because the previews  in jasper working fine. So I guess grooy code inside the fields is not supported, or is it?

I have several cells containing longer text in my DB . In the report preview everything is fine even some linebreaks are correct. But the pdf result only produces one single line so whats going wrong. I do  not know the error?? 
Here the reportpreview 
![blpcahgejpfhmfjh](https://user-images.githubusercontent.com/45485205/49285398-9ad9bc80-f497-11e8-85ce-d3b55cc9ad83.png)

this ist the pdf result with only one line
![gpnidaeemichbnmb](https://user-images.githubusercontent.com/45485205/49285446-b644c780-f497-11e8-9b75-91373ca07855.png)

So do you have any idea whats going wrong?

Thank a lot for your help

**Comment by kstan79** [comment]
You have 2 issue. Regarding groovy it not natively support, cause phpjasperxml is php project, it cant run effectively with groovy and we not intend to support it (there is some trial performance is 10x slower). we use some hack like `${field1}=='Y'` for control presentation.

Again, you share not use jasperreportstudio as benchmark cause it is php project.

Regarding 2nd issue, I think you shall check 'Print When Detail Over Flow'.

**Comment by toothlesstiger** [comment]
Thanks a lot 2nd Issue is solved! Best regards!

**Comment by kstan79** [comment]
ok
