### ISSUE TITLE
generating font did not work

### ISSUE THREAD

**Issue by toothlesstiger** [SIMITGROUP/phpjasperxml#31]
Hi Ks Tan,

well I copied e.g. Calibri.ttf in the same folder with the tcpdf_addfont.php and i wrote a batch like:

D:\...mypath...\phpjasperxml-master\tcpdf\tools\tcpdf6\tools\tcpdf_addfont.php -b -t TrueTypeUnicode -f 33 -i Calibri.ttf

I started to run the batch from the dos-box but the font is not generated only firefox opens ... the tcpdf_addfont.php

So what is going wrong maybe I did not get the method correctly.

Best regards Holger

**Comment by kstan79** [comment]
please refer below image:
<img width="579" alt="screenshot 2018-12-03 at 11 01 52 am" src="https://user-images.githubusercontent.com/1889979/49350706-fc459980-f6ea-11e8-9311-a8cb3e679fbd.png">

**Comment by toothlesstiger** [comment]
Hi again

here is the code I'm trying: (windows cmd box)

D:\Xampp\php>php D:/somepath/phpjasperxml-master/tcpdf/tools/tcpdf6/tools/tcpdf_addfont.php -b -t TrueTypeUnicode -f 33 -i D:/Calibri.ttf 
I got this ERROR MESSAGE:
Can't write to D:\somepath\phpjasperxml-master\tcpdf\tools\tcpdf6/fonts

So still fighting for the font :-) but no idea what to change. I think the php file is running because typing
D:\Xampp\php>php D:/somepath/phpjasperxml-master/tcpdf/tools/tcpdf6/tools/tcpdf_addfont.php -b -t TrueTypeUnicode -f 33 -i 
the ERROR is missing input fonts ... occurs

Best Regards H.

**Comment by kstan79** [comment]
i think because of u use windows and it not support symlink folder. u can remove tcpdf6/fonts, and recreate a new tcpdf6/fonts. try again

**Comment by toothlesstiger** [comment]
I will attach the files here :-)




[fonts.zip](https://github.com/SIMITGROUP/phpjasperxml/files/2642830/fonts.zip)

**Comment by toothlesstiger** [comment]
So hope that works for you aswell! Thank s a lot again

**Comment by kstan79** [comment]
i'd added the font into font directory so that you no need to worry in future, however take your own risk.
