### ISSUE TITLE
some variable not loading like colum coun in produced pdf

### ISSUE THREAD

**Issue by DrShail23** [SIMITGROUP/phpjasperxml#32]
Hi , in Phpjasperxml why i not see some variable in pdf , i can see  in preview in ireport but cannot see in php generated pdf

**Comment by kstan79** [comment]
can give some example?

**Comment by DrShail23** [comment]
like $V{COLUMN_COUNT}  variable not show in generated pdf but seen in preview , And if i Add  a $V{REPORT_COUNT} variable then it show in generated pdf but diffrence is it start with 0 not with 1 , but in preview it start with 1 , And Other prbolem is if i add a  this syntax "$F{med_type}+"."+$F{med_name}" then it work but if i add it in variable then load it not work . and i cannot format a date , if i formate it show me  a 1-1-1970 Date .
this is  a generated pdf with phpjasperxml
![php_genrated_pdf - copy](https://user-images.githubusercontent.com/45815260/49871463-560d3880-fe3c-11e8-8d33-7a9846896431.png)

this is  a privew in ireport
![preview_pdf](https://user-images.githubusercontent.com/45815260/49871503-73420700-fe3c-11e8-9528-a3de8dd7f2a3.png)

**Comment by kstan79** [comment]
OK, handling variable in phpjasperxml is not as good as handle field and parameter. 
1. $V{REPORT_COUNT} should start from 1 as you said, and it is a bugs. You may try swap between 1.0 and 1.1 see is that helpful?
2. $V{COLUMN_COUNT} is not supported cause we never use this variable before. If you really need this, you may add your support in abstractPHPJasperXML->analyse_expression() 
3. Format date you may refer to abstractPHPJasperXML->formatText() see what is supported pattern
4. As mentioned earlier, variable support is still very basic (basic sum/avg/max/min). Most of the time we use work arround method such as:
a. calculate value from sql query
b. calculate outside and submit parameter 

Most of the time we use phpjasperxml as formating engine, so I dont think we will put much effort improve variable computation. However, we welcome you to improve the library so others community user can get benefit.

**Comment by DrShail23** [comment]
Thanks for your feedback ,  Where i can download 1.1 version Still i m using 0.9d

**Comment by kstan79** [comment]
Just git clone latest master

**Comment by DrShail23** [comment]
How can we Set  top margin right margin , Like Page Setting from Php array

**Comment by kstan79** [comment]
i can understand what you mean, if it is new issue u may close this issue and create another

**Comment by DrShail23** [comment]
No Sir it not A issue but i just ask you regarding how can we change a margin of generated PDF with php input from php Application

**Comment by DrShail23** [comment]
Hi, $V{PAGE_NUMBER} , and "Page "+$V{PAGE_NUMBER}+" of"" " + $V{PAGE_NUMBER} ,  Print only in First Page  in version 1.1 , Not Print in Page 2 and other  But in  version phpjasperxml0.9d It Print in All Page Normaly   ,

**Comment by kstan79** [comment]
variable is not process nicely sometimes. will remain this issue open till fix

**Comment by kstan79** [comment]
Oh you use column header or footer, we seldom use that, since pager header and footer can achieve same result. Does it work at page header or footer?

**Comment by DrShail23** [comment]
it work in Page Header but Not in Page Footer

**Comment by kstan79** [comment]
Oh you didn’t define last page footer?

**Comment by DrShail23** [comment]
In last Page Footer it Show but in Page Footer It not Show e. g If my Report has a 3 three Page then Page 1 of 3 Show in First Page but On Second It Not Show Page 2 of 3 And Page three it Not Show page 3 of 3, And if i Put it on Last Page Footer Then it Will Show only on 3rd Page  That Page 3 of 3, Not on First and Second  Page. In short, Whatever we put on Page Footer and Column Footer Will Show only on First Page only Not on Further Page. And in Version 0.9d It Shows in All page.

**Comment by kstan79** [comment]
you can add variable $phpjasperversion and set to 1.0, cause it use similar function with 0.9d. 1.1 was major modified on analyse expression. you can see how '$phpjasperversion' use at below url:
https://github.com/SIMITGROUP/phpjasperxml/blob/master/PHPJasperXML.inc.php

**Comment by kstan79** [comment]
will look into this issue in after next week.

**Comment by DrShail23** [comment]
sir , It Not work in 1.0  only in 0.9d  Version it work

**Comment by kstan79** [comment]
oh, there is limitation in this, u need make text box wider.  when text box width small it will chop over the content. but we need full {{:ptp:}} to replace as page number

**Comment by DrShail23** [comment]
Break option With page break in detail bamd work or not

**Comment by kstan79** [comment]
Page break is functioning but it may look weird

**Comment by kstan79** [comment]
this repository closed, use new repository with new code base instead:
https://github.com/SIMITGROUP/phplibs
