### ISSUE TITLE
No Sir it not A issue but i just ask you regarding how can we change a margin of generated PDF with php input from php Application

### ISSUE THREAD

**Issue by kstan79** [SIMITGROUP/phpjasperxml#33]
_Originally posted by @DrShail23 in https://github.com/SIMITGROUP/phpjasperxml/issues/32#issuecomment-447272189_

**Comment by kstan79** [comment]
I cant imagine what kind of result you wish to achieve, but you may try hack variable in `$PHPJasperXML->page_setting()`. 

after 
```php
$PHPJasperXML->simplexml_load_string() // or $PHPJasperXML->simplexml_load_file()
//add your customize code / function here.
```

**Comment by DrShail23** [comment]
i just wan to manually change  margin of pdf from php  of this function 
public function page_setting($xml_path=[]) {
        $this->arrayPageSetting["orientation"]="P";
        $this->arrayPageSetting["name"]=$xml_path["name"];
        $this->arrayPageSetting["language"]=$xml_path["language"];
        $this->arrayPageSetting["pageWidth"]=$xml_path["pageWidth"];
        $this->arrayPageSetting["pageHeight"]=$xml_path["pageHeight"];
        if(isset($xml_path["orientation"])) {
            $this->arrayPageSetting["orientation"]=substr($xml_path["orientation"],0,1);
        }
        $this->arrayPageSetting["columnWidth"]=$xml_path["columnWidth"];
        $this->arrayPageSetting["leftMargin"]=$xml_path["leftMargin"];
        $this->arrayPageSetting["rightMargin"]=$xml_path["rightMargin"];
        $this->arrayPageSetting["topMargin"]=$xml_path["topMargin"];
        $this->y_axis=$xml_path["topMargin"];
        $this->arrayPageSetting["bottomMargin"]=$xml_path["bottomMargin"];
    }
like we send $PHPJasperXML->arrayParameter=array("parameter1"=>1);
 so in this $PHPJasperXML->page_setting().
what i have to write , 
can we send in array  or what 
$PHPJasperXML->page_setting(array(topMargin)). or else

**Comment by kstan79** [comment]
No there is no any build in function for that, you need to create addition method, like 
```php
public function overridePageSetting($arr)
{
      //override desire variable 
}
```
Call that after xml loaded.

**Comment by kstan79** [comment]
it support different page size, and support both Landscape/Portrate

**Comment by kstan79** [comment]
I need to highlight at this moment it only support px, no mm, cn, inch is supported yet

**Comment by kstan79** [comment]
no more conversation, consider solved
