### ISSUE TITLE
Break option With page break in detail bamd work or not

### ISSUE THREAD

**Issue by kstan79** [SIMITGROUP/phpjasperxml#34]
_Originally posted by @DrShail23 in https://github.com/SIMITGROUP/phpjasperxml/issues/32#issuecomment-447888385_

**Comment by kstan79** [comment]
page break u required to park as lowest sequence in specific band, it not base on highest 'y'. Regarding work or not work u may try it. most of the time we use break at page title, summary, or last page footer, you may try at detail band and let us know.

**Comment by DrShail23** [comment]
i m making sale bill of medicine  so i need to  keep minimum 10 medicine in detail band and other medicine o n next page for that i need a  page break in detail , other way is i have to increase column footer band height so it adjust accroding to it .

**Comment by kstan79** [comment]
u shall make your detail band small, with single row height. regarding page break it will handle automatically

**Comment by kstan79** [comment]
no more conversation, consider closed
