### ISSUE TITLE
Month extract from Mysql Date

### ISSUE THREAD

**Issue by DrShail23** [SIMITGROUP/phpjasperxml#35]
Hi , if i use $F{month_date}.getMonth() this in group expression then it work in ireport but in generated PDf it not work and all Result not seprated by group by month , Is ther any other way to do it , My query is  SELECT
    SUM(sale_amt) AS month_sale_amt,
    SUM(sale_extraamt) AS month_sale_extraamt,
    SUM(sale_netamt) AS month_sale_netamt,
    DATE_FORMAT(sale_date, '%Y-%m-%d') AS month_date
FROM
    ayush_ph.sales
GROUP BY DATE_FORMAT(sale_date, '%Y-%m-%d') ,  i wan to group result by month . I wan to like this 
![monthgroup](https://user-images.githubusercontent.com/45815260/50287349-79616480-0488-11e9-8868-d459a7b2fde4.png)
But Genrated PDf  is like this 
![gnerated](https://user-images.githubusercontent.com/45815260/50287370-87af8080-0488-11e9-8dd3-0c6697d878b7.png)

**Comment by kstan79** [comment]
"$F{month_date}.getMonth()" is java syntax and it not compaible with php, you shall process list at mysql level
