### ISSUE TITLE
Question : When Subreport work in verion 1.1

### ISSUE THREAD

**Issue by DrShail23** [SIMITGROUP/phpjasperxml#36]
When Subreport Work in Version 1.1 , And Subrport Suport in only Detail band or work in Other band also ?

**Comment by kstan79** [comment]
subreport work in all band, but at detail band is not perfect cause it can scale effectively. 
https://github.com/SIMITGROUP/phpjasperxml/blob/master/sampleimage/soa.png is using sub report letter head
