### ISSUE TITLE
variable in footer not display

### ISSUE THREAD

**Issue by vivinrokt** [SIMITGROUP/phpjasperxml#37]
hello,
why variable like print page number can't displayed in pdf? i try to edit the design in ireport. but it's work correctly in ireport. i created page number in page footer band.
i created my report using ireport 5.6.0.

**Comment by kstan79** [comment]
page number should work nicely if you drag from pallete, no matter at footer band or etc. u use version 1.1?

**Comment by vivinrokt** [comment]
I use version 1.1. but it's not work in footer band. 
but it's work if i drag page number to background.
just not work in footer band.

**Comment by kstan79** [comment]
I’m strange, let me check again

**Comment by abyga1966** [comment]
Hello, I have the same problem, the fields or elements that I put in the footer band are not visible in the pdf. However when I maximize the height of the page footer band the information is visible.

If I put a height of more than 500 px in the properties of the page footer band is visible.

I am using XAMPP for Windows 7.1.26. and phpjasperxml with version 1.1 and Jaspersoft studio 6.6.0

Thanks.

**Comment by abyga1966** [comment]
Hi, the solution i found is use the last page footer band. Work for me.

Thanks.

**Comment by kstan79** [comment]
ya, at the moment we need page footer and last page footer both appear
