### ISSUE TITLE
TextField overlap and subreport not work perfect in 0.9d

### ISSUE THREAD

**Issue by DrShail23** [SIMITGROUP/phpjasperxml#38]
HI , I Created a Report in ireport 5.6.0 , In it My Report Preview is Like this 
![preview_pdf](https://user-images.githubusercontent.com/45815260/50511717-bfd04800-0ab4-11e9-8f3c-0d77f4bb14a9.png)
but After Generated PDf with 0.9d Version  it like this 
![geerated_pdf _0 9d](https://user-images.githubusercontent.com/45815260/50511750-de364380-0ab4-11e9-91fc-3bb0b8630f68.jpg)
And my Designer View is this  in it i set 
Examination  Properity : Position type : Fix Relative to top , Strech type : No Strech , Print Repated Value : True , 
$F{visit_examination Properity : Position type : Fix Relative to top , Strech type : No Strech , Print When Detail Overflow  : True ,  Strech With OVerflow : True.
Lab  Properity : Position type :Float , Strech type : No Strech , Print Repated Value : True , 
$F{visit_lab_report} Properity : Position type :float  , Strech type : No Strech , Print When Detail Overflow  : True ,  Strech With OVerflow : True.

![designer_view](https://user-images.githubusercontent.com/45815260/50511762-e8584200-0ab4-11e9-8ceb-396bd8d65d66.png)
Subreport View 👍 
![subreport_design](https://user-images.githubusercontent.com/45815260/50512025-f2c70b80-0ab5-11e9-964e-3051e852e915.png)
So What Can be Change  in Setting or Any one

**Comment by kstan79** [comment]
Can give screenshoot?

**Comment by DrShail23** [comment]
HI , this is a  generated pdf with ireport 
![privewinireport](https://user-images.githubusercontent.com/45815260/50554976-04452900-0ceb-11e9-9069-6badfbfaf6f7.png)
and this  is a design view 
![designview](https://user-images.githubusercontent.com/45815260/50554981-145d0880-0ceb-11e9-93e2-f8449fb93338.png)
And this a PDF geenration with Phpjasperxml 1.1 Version
![generated_pdf](https://user-images.githubusercontent.com/45815260/50554985-276fd880-0ceb-11e9-9abc-c59db2b2030a.png)

And i Set a Property of 
$F{visit_examination} to  Print When Detail Overflows :	true ,  Stretch With Overflow	: true
and 
$F{visit_lab_report}  to  Print When Detail Overflows :	true ,  Stretch With Overflow	: true

**Comment by kstan79** [comment]
ok, i forget to mention phpjasperxml only detail band will grow, others band wont. i think thats the reason cause that.

**Comment by DrShail23** [comment]
Hi but i removed Subreport in Last post . eventhough  text overlap

**Comment by kstan79** [comment]
it doesnt related to subreport anymore. your text content in group larger then group height.
