### ISSUE TITLE
No print Variables, and varaible expresion

### ISSUE THREAD

**Issue by esbxp2013** [SIMITGROUP/phpjasperxml#4]
Still in diapers, you can not print variables or expressions myVar = 1 + 6 because the reader xml, just do not read, nor notes footer, "Page" may only be, if it does not say that word then do not write anything in the expression string, need a lexical analysis of the expressions, something like:

$ result = execute_string ("5 + 9 + $ myVar");
Could be some LUA interpreter, Ruby, or anything that can interpret ...

Keep it up !!!
Greetings !!!

Hola:

Aun esta en pañales, no se pueden imprimir variables, ni expresiones myVar = 1 + 6, porque el lector del xml, simplemente no las lee, tampoco las notas del pie de pagina, solo debe decir "Page", si no dice esa palabra entonces no escribe nada en la expresion string, falta un analisis lexico de las expresiones, alpo como:
 $resultado = EXECUTE_STRING(" 5 + 9 + $myVar");
Podria ser algun interprete LUA, RUBY, o alguna cosa que pueda interpretarlo...

Sigan adelante !!!
Saludos !!!

**Comment by kstan79** [comment]
hi can ask in english? But since this issue has been long time i believe it closed
