### ISSUE TITLE
Multiple columns

### ISSUE THREAD

**Issue by GarciaLozano** [SIMITGROUP/phpjasperxml#40]
Hi again!
I can't get a multiple columns report. Is it a bug or am I in a mistake with some parameters of report? I need use 2 columns but phpjasperxml always render only one. When I prevew it on iReports it is shown with 2 columns but when phpjasperxml render report only one is displayed.
Thanks in advance

**Comment by kstan79** [comment]
hi, multiple column is not support due to initial design never define this requirement. i dont think it can support easily future.
