### ISSUE TITLE
How to add multiple report (xml) to one PDF

### ISSUE THREAD

**Issue by moonrinnn** [SIMITGROUP/phpjasperxml#43]

**Comment by kstan79** [comment]
You can initialize phpjasperxml multiple time either with loop or manually, then outpage(‘F’,$pathtopdf) file using parameter ‘F’ instead of ‘I’ (in-line). 2nd para is desired destination pdf file path you wish to store.

Then just use pdfconcat or etc tools to combine into one.

**Comment by kstan79** [comment]
no reply, assume issue solved
