### ISSUE TITLE
i-Report Sub-report not showing : php 

### ISSUE THREAD

**Issue by amutota** [SIMITGROUP/phpjasperxml#44]
I have situation where I run report produced using i-Report.
A main Report contains three sub-reports, and all are working fine when previewing them on Jasper i-Report Design Studio. 
I call the main Report using php script. However, sub-reports content not showing at all. As script runs, the main report only displays sub-reports SQL strings on the browser. If I remove sub-reports from the Main Report, then the main report displays nicely.
The same concept used in Java web application and worked just nice; I am not so sure, what I missed out in php. Could anyone help?

Many thanks in advance.

**Comment by kstan79** [comment]
Hm... are you use latest version? Beside, you use 1.1 or 1.0 class?

**Comment by amutota** [comment]
Hi there, I am using the following version per attachment.
![files version](https://user-images.githubusercontent.com/51090292/58853761-8b803980-869b-11e9-844d-1d2a97f89103.jpg)

**Comment by kstan79** [comment]
Use latest version from this repository plz

**Comment by amutota** [comment]
Hi there, I am using the following version per attachment.

**Comment by amutota** [comment]
I will highly appreciate if it works. 
I am a bit new here. Any link where I can find it on this repository, plz?

**Comment by kstan79** [comment]
https://github.com/SIMITGROUP/phpjasperxml Then ‘clone or download’

**Comment by amutota** [comment]
I just used the version 1.1 from this repository, tested it. However, I am not quite sure if it is the latest version you referred to me. Reports without a Sub-Report work fine, but once there is a sub-report then not does not work. shows 'No data found'.
Files used are under..:
include_once('phpjasperxml-master/tcpdf/tcpdf.php');
include_once("phpjasperxml-master/version/1.1/PHPJasperXML.inc.php");

Any idea why it not showing sub-reports?

But, I also noticed after configured sample work, there is a link indicates; “Sample 3 Sub Reports (not yet fix)”

**Comment by amutota** [comment]
I just used the version 1.1 from this repository, tested it. However, I am not quite sure if it is the latest version you referred to me. Reports without a Sub-Report work fine, but once there is a sub-report then not does not work. shows 'No data found'.
Files used are under..:
include_once('phpjasperxml-master/tcpdf/tcpdf.php');
include_once("phpjasperxml-master/version/1.1/PHPJasperXML.inc.php");

Any idea why it not showing sub-reports?

But, I also noticed after configured sample work, there is a link indicates; “Sample 3 Sub Reports (not yet fix)”

**Comment by kstan79** [comment]
As you can see from below is the image, subreport is working fine in phpjasperxml. Issue is jrxml SUBREPORT_DIR parameter value is configured wrongly (follow my computer setting). I'd switch to relative path './' and commit the changes, you can try again.

Sorry of this mistake.

<img width="759" alt="Screenshot 2019-06-14 at 8 01 44 PM" src="https://user-images.githubusercontent.com/1889979/59508076-536cc800-8edf-11e9-8c88-9e01a9f19f5d.png">

**Comment by kstan79** [comment]
no further reply, assume issue solved

**Comment by amutota** [comment]
Nothing worked for me yet. I am coming back to this project on 10 July 2019.

**Comment by amutota** [comment]
Complements of the New Year, 2020!
Below is a last year submission. Please follow it and assist if there is an update for php sub-report that might work for us.


"I have a situation where I run report produced using i-Report.
A main Report contains three sub-reports, and all are working fine when previewing them on Jasper i-Report Design Studio.
I call the main Report using php script. However, sub-reports content not showing at all. As script runs, the main report only displays sub-reports SQL strings on the browser. If I remove sub-reports from the Main Report, then the main report displays nicely.
The same concept used in Java web application and worked just nice; I am not so sure, what I missed out in php. Could anyone help?

Many thanks in advance."

**Comment by kstan79** [comment]
your subreport sample work well?

**Comment by amutota** [comment]
Yes, it is working fine when previewing it on Jasper i-Report Design Studio.

**Comment by amutota** [comment]
I call the same sub-report in Java, but works just fine. I am not sure what setting (if any) I have missed in php

**Comment by amutota** [comment]
> 
> 
> your subreport sample work well?

Yes, it is working fine when previewing it on Jasper i-Report Design Studio.

**Comment by amutota** [comment]
Good day,
It seems to me that there is no solution to how to integrate ireport subreport with php. Is not it?

**Comment by amutota** [comment]
Is subreport versions specific to php and jasper studio or something?

**Comment by kstan79** [comment]
PHPJasperXML support minimal level of subreport,  you have to refer "Sample 3" in project. If you can see similar image as above reply (Green box text show Sub Report Content: 1). Then your sub report configuration is working well. I want to highlight we are using Jasper Report Studio to design the layout and produce xml. However it is php project and have very limited compatibility with Java project.

**Comment by amutota** [comment]
Good day,

The sub-report sample works well when previewed on the Jasper Studio. But
it does not work at all on browser.

Kind regards,
Andreas

**Comment by kstan79** [comment]
The sample3 shall work well as the image show. To be confirm your use case, You tried the sample 3 with the sample db in repository?

**Comment by amutota** [comment]
I might have misplaced  sample3 somewhere. If you have a link to it, can
you forward it to me so go try it?

Kind regards,
Andrea

**Comment by kstan79** [comment]
You can explore sample/index.php

**Comment by kstan79** [comment]
this repository closed, use new repository with new code base instead:
https://github.com/SIMITGROUP/phplibs
