### ISSUE TITLE
 List elements of the Jaspersoft

### ISSUE THREAD

**Issue by edescalona** [SIMITGROUP/phpjasperxml#45]
Hi, I would like to know if the "List" elements of the Jaspersoft are implemented in the "phpjasperxml-master" library of php, because when I execute it, it does not show any errors but the list is not displayed either.

I am using class 1.1, greetings.

**Comment by kstan79** [comment]
Hi at the moment we no implement it yet. In short term no any plan yet. If you wish to implement it we can provide guidance.

**Comment by edescalona** [comment]
Ok thanks. 
Now I am working on some things and I did not have much time but later if I would be interested in doing it, I would contact you so that I could get some guidance or if you want you can tell me what are the classes that I should take into account and have some idea, greetings have a good day.

**Comment by kstan79** [comment]
OK
