### ISSUE TITLE
Unable to generate xlsx

### ISSUE THREAD

**Issue by wongdh** [SIMITGROUP/phpjasperxml#46]
Environment: Win10Pro, IIS 10, PHP 7.3.1

I am able to generate PDF, but when trying to output to XLSX following error occurs. please advice. thanks

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ....\tcpdf\tcpdf.php on line 22975

Fatal error: Uncaught Error: Call to undefined function left() in ....\version\1.1\ExportXLS.inc.php on line 1953

**Comment by kstan79** [comment]
fixed.

**Comment by kstan79** [comment]
no further reply, assume issued solved
