### ISSUE TITLE
Different generated output from PHPJasperXML vs Jaspersoft Studio

### ISSUE THREAD

**Issue by mohamadyuzrie** [SIMITGROUP/phpjasperxml#49]
Hi, I have a problem when generating the output. Please refer to the attached screenshots.

Problem: 
1. Some texts seems to appear in Times New Roman and some in SansSerif randomly
2. Column Footer elements does not appear

**Screenshot 1: Generated from PHPJasperXML**

![inconsistent font](https://user-images.githubusercontent.com/51981484/61989815-54a91d00-b067-11e9-8b6a-519b87b66f12.PNG)

**Screenshot 2: Generated from Jaspersoft Studio / The output I want**

![original](https://user-images.githubusercontent.com/51981484/61989816-5541b380-b067-11e9-926c-a24d3e8028bc.PNG)

Btw, I should mention that I've seen another similar closed issue, which was about the usage of _groovy_ and overflowed _text_ and I don't think, the problem is the same here. I'm using Java language on Jasper Studio.

**Comment by kstan79** [comment]
You shall define both page footer and last page footer

**Comment by mohamadyuzrie** [comment]
Hi kstan,

The following problem is resolved when I used Last Page Footer. Thanks

> 2. Column Footer elements does not appear

However the font problem still remains. Do you have advice for that?

> 1. Some texts seems to appear in Times New Roman and some in SansSerif randomly

**Comment by mohamadyuzrie** [comment]
Another thing I noticed, the border / vertical text alignment didn't seem to work properly... If you see the my header (in blue background), they are not how they appear in JasperSoft Studio. The decimal places too is affected even though I passed as string...

**Comment by mohamadyuzrie** [comment]
I noticed, if I dd($out) from any of the band (i.e.: detail(), pageHeader(), etc...)

I get this response:
```
array:26 [▼
  "type" => "MultiCell"
  "width" => 280
  "height" => 15
  "txt" => "$F{invoice__ACC_HOLDER}"
  "border" => 0
  "align" => "L"
  "fill" => 0
  "x" => 0
  "y" => 130
  "font" => "SansSerif"                 // so I'm assuming the font failed because it can't find this font (I'm doing this from Windows maybe that's why the name is SansSerif instead of freeserif)
  "pdfFontName" => null
  "fontstyle" => "B"
  "fontsize" => 11
  "hidden_type" => "field"
  "soverflow" => "false"
  "poverflow" => "false"
  "uuid" => SimpleXMLElement {#456 ▶}
  "printWhenExpression" => ""
  "link" => ""
  "pattern" => null
  "linktarget" => ""
  "writeHTML" => false
  "isPrintRepeatedValues" => null
  "rotation" => ""
  "valign" => "C"
  "elementid" => 1
]
```
When I go through the vendor files in TCPDF, I found that there's no font for that, so I'm guessing I'll need to change the font manually on the JRXML file to be _helvetica_ if its a sans serif font and _times_ if I'm using Times New Roman.

. . .

And so I tried it and it worked. So I'm gonna close this issue now. A note for anyone facing this issue, the solution/workaround is to all occurence of the **Times New Roman** to **times** or **SansSerif** to **helvetica** from the JRXML.
