### ISSUE TITLE
Error while first run

### ISSUE THREAD

**Issue by filipecoelho** [SIMITGROUP/phpjasperxml#5]
I cloned this repo, try run and i give this error:
Notice: Undefined property: PHPJasperXML::$footerbandheight in /Users/filipecoelho/Sites/phpjasperxml/class/PHPJasperXML.inc.php on line 226

**Comment by kstan79** [comment]
u may try again?

**Comment by kstan79** [comment]
but it has been long time so i simply close it.

**Comment by hemimm** [comment]
very simple, PHPJasperXML-1.0-inc is not compatible with JasperSoftc Studio

**Comment by hemimm** [comment]
and PHP7
