### ISSUE TITLE
Not included pattern from Jaspersoft Studio

### ISSUE THREAD

**Issue by mohamadyuzrie** [SIMITGROUP/phpjasperxml#50]
Hi kstan,

(This is just a question)
I noticed the patterns that's default in Jaspersoft Studio 6.8.0 is not included in `abstractPHPJasperXML.inc.php` at line 2559 `protected function formatText()`. 

For now, the only option is for me to put in my own pattern (the one from Jaspersoft Studio) into `abstractPHPJasperXML.inc.php`. The question I'm asking is:

- Will these patterns be added in future version? 
- Or will we be able to define our own pattern in the future?

### References:
Screenshot 1: From `abstractPHPJasperXML.inc.php`
![pattern](https://user-images.githubusercontent.com/51981484/62020255-d5e1ea80-b1f4-11e9-998c-c7969cbfd7b1.PNG)

Screenshot 2: From Jaspersoft Studio
![pattern from jss](https://user-images.githubusercontent.com/51981484/62020251-cebadc80-b1f4-11e9-905d-f816e69e79ec.PNG)

**Comment by kstan79** [comment]
you may define your own pattern and send me PR.

**Comment by mohamadyuzrie** [comment]
Currently my scope switched focus from JasperReports.. I'll probably send PR on a later date, I'll close this issue for now
