### ISSUE TITLE
multiple sub reports to main report, but weird showing of sub reports

### ISSUE THREAD

**Issue by ujandphp** [SIMITGROUP/phpjasperxml#51]
Dear Author,
 Can you guide regarding correct showing up of sub reports in main report, i can get correct view
in netbeans designer preview but not while generating pdf thorough codeigniter.
I'm attaching my designer preview and code output please review and guide us.
output through Code:
[report_name.pdf](https://github.com/SIMITGROUP/phpjasperxml/files/3513125/report_name.pdf)
Designer Preview:
![image](https://user-images.githubusercontent.com/54241045/63225820-63ac6680-c1f2-11e9-9e2d-68ca24e19bdb.png)

**Comment by kstan79** [comment]
You are using subreport in detail band? Can show the property of subreport?

**Comment by ujandphp** [comment]
Yes i have tried simply putting subreport in detail band of Main Report, Here is details of property:
**Subreport Expression** 	$P{SUBREPORT_DIR} + "reportTemplate_1_subreport1.jasper"
**Expression Class**	java.lang.String
**Using Cache**	true
**Parameters Map Expression**	Blank
**Connection type**	Use a connection expression
**Connection Expression**	$P{REPORT_CONNECTION}
**Data Source Expression**	BLANK
**Parameters**	4 properties defined
**Return Values**	No return values defined
If you guide best usecases for using subreports in a main report, it will be very helpfull.

**Comment by ujandphp** [comment]
@kstan79 for your reference today i have tried from a different system with JDK 1.8.0 and netbeans plugin i have actuall complie the jrxml and my subreports came but there was a problem. I am using two subreport and when i am seeing in designer it comes perfect but during code output it's overlapping. 
N.B this time i didn't show up with details band

**Comment by kstan79** [comment]
Your sub report .jrxml is it inside same directory? Beside, try define some hardcode sql inside subreport and check whether it display correctly? You can check sample in the repository whether the subreport show?

**Comment by ujandphp** [comment]
@kstan79 Yes my sub reports are in the same directory, i have tested multiple scenario here is the findings:
1)Sub report has multiple rows so i keep it in details band and subtotal are in summary column, and in main report i show in summary section.
2)Sub report has multiple rows so i keep it in group footer band and subtotal are in summary column,  in main report i put it in summary section.
Results:
1) Only Subtotal are coming
2) every thing overlapping
So my question is where should i put my sub reports.

**Comment by kstan79** [comment]
hi, in this case you shall not use subreport, you shall use detail band instead. the sub report case is good for centralize manage many printformat (example, document letter head)

**Comment by kstan79** [comment]
this repository closed, use new repository with new code base instead:
https://github.com/SIMITGROUP/phplibs
