### ISSUE TITLE
text rotation

### ISSUE THREAD

**Issue by 12gods** [SIMITGROUP/phpjasperxml#53]
load file "rotate.jrxml"
i want to rotate a text label but when i use the parameter Left the export not working

the problem is on variables pdf->k and pdf->h because there are null
is there any solution?

f( $angle!=0  )
            {
                $angle*=M_PI/180;
                $c=cos($angle);
                $s=sin($angle);
                $cx=$x*$this->pdf->k;
                $cy=($this->pdf->h-$y)*$this->pdf->k;
                $this->pdf->_out(sprintf('q %.5f %.5f %.5f %.5f %.2f %.2f cm 1 0 0 1 %.2f %.2f cm', $c, $s, -$s, $c, $cx, $cy, -$cx, -$cy));
            }

**Comment by kstan79** [comment]
how your orientation/degree?

**Comment by 12gods** [comment]
as my sample i use static text and the orientation is  rotation="Left"


`<staticText>
				<reportElement x="2" y="222" width="10" height="45" uuid="9ccb6d10-ed3e-4773-9998-582d28e75404">
					<property name="com.jaspersoft.studio.unit.x" value="pixel"/>
				</reportElement>
				<box>
					<leftPen lineWidth="1.0"/>
					<bottomPen lineWidth="1.0"/>
					<rightPen lineWidth="1.0"/>
				</box>
				<textElement textAlignment="Center" rotation="Left">
					<font pdfFontName="" isPdfEmbedded="true" fontName="Arial" size="5"/>
				</textElement>
				<text><![CDATA[code]]></text>
			</staticText>`

**Comment by kstan79** [comment]
hi, i'm tried using your label it seems draw text as expected, but the border seems not cover the text correctly
<img width="229" alt="Screenshot 2019-10-21 at 10 01 54 PM" src="https://user-images.githubusercontent.com/1889979/67212131-70497700-f44e-11e9-9a1a-9b461ba5149b.png">
This issue I will leave it open, however wont fix immediately. To work arround you can create another rectangle to cover the text.

**Comment by kstan79** [comment]
this repository closed, use new repository with new code base instead:
https://github.com/SIMITGROUP/phplibs
