### ISSUE TITLE
phpjasperxml / print when expression

### ISSUE THREAD

**Issue by Danillosdd** [SIMITGROUP/phpjasperxml#55]
From Brazil,

I can't execute phpjasperxml with fields that have no validation when print; does not obey validation.

**Comment by kstan79** [comment]
Hi Danillosdd
can you give proper example?

**Comment by Danillosdd** [comment]
I use php asxml with ireport.

In my ireport there are fields that have a validation for this field to be printed or not.

Example: The field will only appear when the code is different from 12.

testing on ireport works.

However, when calling the report by phpjasperxml, it does not recognize the validation, as it appears in all situations.

(The library documentation in Brazil is terrible)

thanks.

**Comment by kstan79** [comment]
I can't see your sample field setting. However I assume you are using Java syntax which is not working. 

** Don't user java syntax in your expression (field, print when expression and etc).  Example: `$F{field1} == $F{field2}` is working and `$F{field1}.equal($F{field2})` is not.

**Comment by Danillosdd** [comment]
não estou utilizando sintaxe java, está assim:

$F{codigo} != 12

**Comment by Danillosdd** [comment]
Another situation is that when calling a subreport, the letters of the subreport are misconfigured; It is as if the subreport was not working charset.

Special characters do not work.

like: ^, ~, ´ ...

**Comment by Danillosdd** [comment]
another doubt is ...
when I have a .jrxml that is calling a subreport.

in phpjasperxml this sureport comes in a new page instead of loading on the current page.

is that so?

because when testing by ireport the subreport comes on the same page

**Comment by kstan79** [comment]
> I'm not using java syntax, it looks like this:
> 
> $ F {code}! = 12

Please show xml content of the box here. And, others issue please create another issue.

**Comment by Danillosdd** [comment]
https://www.dropbox.com/sh/w0qnzy1vwib4itq/AABJAyYI0A3ZbSgROde_xtjva?dl=0

**Comment by kstan79** [comment]
Dear Danillosdd,
from your sample I can't track what is the root cause. You need to do it by yourself.
Uncomment line 2403 `echo $evalstr."<br/>";`

from  **version/1.1/abstractPHPJasperXML.inc.php**  and re-run the report. It give you junk of eval content. You may troubleshoot the evalstr act accordingly. Good luck!

**Comment by kstan79** [comment]
this repository closed, use new repository with new code base instead:
https://github.com/SIMITGROUP/phplibs
