### ISSUE TITLE
subreport new page

### ISSUE THREAD

**Issue by Danillosdd** [SIMITGROUP/phpjasperxml#58]
another doubt is ...
when I have a .jrxml that is calling a subreport.

in phpjasperxml this sureport comes in a new page instead of loading on the current page.

is that so?

because when testing by ireport the subreport comes on the same page

**Comment by kstan79** [comment]
u can refer example sample3, it will use same page.

**Comment by lvsan** [comment]
I have try the sample3 but the subreport is not preview. can advise?

**Comment by kstan79** [comment]
u did install the sample db?

**Comment by lvsan** [comment]
Hi ,

 

I have install the db and try. Only do not why I copy and paste to the project I use will not working.

 

Thanks.

 

Regards,

 

Low Voon San

Assistant Project Manager

DCS Synthesis Pte Ltd

 

Office :  +65 6282 7655

Fax     :  +65 6742 7451

Email  :  <mailto:vslow@synthesis.bz> vslow@synthesis.bz 

Corporate Video :  <http://www.synthesis.bz/video.html> www.synthesis.bz/video.html

865 Mountbatten Road #05-27 Katong Shopping Centre Singapore 437844

**Comment by kstan79** [comment]
this repository closed, use new repository with new code base instead:
https://github.com/SIMITGROUP/phplibs
