### ISSUE TITLE
issue in retrieving value from stored procedure and also with sum of a colum value as per page

### ISSUE THREAD

**Issue by softhought** [SIMITGROUP/phpjasperxml#59]
page total and the retrieving value from stored procedure is working fine in ireport 
but in the phpjasperxml 
1. the page total/sum is not showing but the group is ok.
2. when i'm trying to fetch data from procedure with parameters it shows 'No data found' but the same jxml file im using in ireport it's  works fine  .

this image is code for the  stored procedure
![1](https://user-images.githubusercontent.com/49486475/69870556-42214780-12d6-11ea-8fc6-9cacaca43c88.PNG)

this image is output of 1st image
![2](https://user-images.githubusercontent.com/49486475/69870558-42214780-12d6-11ea-86fc-8f20f189fd1d.PNG)

this image showing page sum in ireport
![3](https://user-images.githubusercontent.com/49486475/69870559-42b9de00-12d6-11ea-98b5-a1b0d663d5da.PNG)

**Comment by kstan79** [comment]
im not so sure call procedure will work well, if you have issue you may visit here:
https://github.com/SIMITGROUP/phpjasperxml/wiki/Do-something-beyond-standard-data-source

**Comment by kstan79** [comment]
this repository closed, use new repository with new code base instead:
https://github.com/SIMITGROUP/phplibs
