### ISSUE TITLE
Oracle Support?

### ISSUE THREAD

**Issue by vbspcoder** [SIMITGROUP/phpjasperxml#6]
How to make $PHPJasperXML->transferDBtoArray to connect to Oracle

**Comment by kstan79** [comment]
Hi,

Latest version we did tried use pdo but never test it properly, u may use it and feed back.

PHPJasperXML->transferDBtoArray($db_host,$db_user,$db_pass,$dbname,"pdo");

**Comment by kstan79** [comment]
Close ticket  due to no reply sometimes

**Comment by SergioRe** [comment]
@kstan79 Could you put what version of PHP and what version of iReport do you use?

**Comment by kstan79** [comment]
latest 1 will do, i use Tibco Jasper Studio Community Edition 6.8.1

**Comment by kstan79** [comment]
this phpjasperxml end. use latest method.
