### ISSUE TITLE
problem to PHPJasperXML with oracle

### ISSUE THREAD

**Issue by moronen** [SIMITGROUP/phpjasperxml#64]
I have the following code to execute the report:

include_once('Reportes/CostosAFE/phpjasperxml_0.9d/class/tcpdf/tcpdf.php');
include_once('Reportes/CostosAFE/phpjasperxml_0.9d/class/PHPJasperXML.inc.php');
$host="10.172.244.6";
$user="edmadmin";
$password="fajafaja";
$db_or_dsn_name="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = 10.172.244.6)(PORT = 1524)))(CONNECT_DATA =(SID = orip76)(SERVER = DEDICATED)))";
$PHPJasperXML = new PHPJasperXML();
$PHPJasperXML->load_xml_file("Costos_subReporte_Comentarios.jrxml");
$PHPJasperXML->transferDBtoArray($host,$user,$password,$db_or_dsn_name,$cndriver="odbc");
$PHPJasperXML->outpage("I"); 

I have read the documentation and I have seen the function transferDBtoArray(), it receives 5 parameters, I am using php 5.6 I want to know if the entire structure is well defined because nothing is executed, the screen is blank. The data in my database are correct.

the report compiles well in Ireport5.6

I want to connect with Oracle, how would I do it? Thanks in advance.

**Comment by kstan79** [comment]
you can connect to oracle using pdo or odbc method. I'm feel weird with your odbc string, if you can't connect with 'odbc' then try 'pdo' instead:
$cndriver='pdo';
$PHPJasperXML->transferDBtoArray($db_host,$db_user,$db_pass,$dbname,$cndriver); 
if you wish to know more regarding connection, may refer abstractPHPJasperXML.inc.php, line 107.

Good luck

**Comment by kstan79** [comment]
no reply, assume issue closed
