### ISSUE TITLE
Missing classes on VideoConferencingSystem-master project

### ISSUE THREAD

**Issue by amutota** [SIMITGROUP/phpjasperxml#65]
First, I would to thank you for sharing your source codes for java project named "VideoConferencingSystem-master"

I tried to run the source codes in java system IDE, only the server works fine.
But the Video Conferencing is not working. There seems to be some missing objects that are called in other classes. Or Perhaps I am missing some JAR files?

The classes/JFrames are it follows:

ListenThread missing ListenThreadListener
MyURLPlayer missing AudioBufferControl
Personal missing ApplicationStarter
PrivateMessageListener missing  PrivateMessage
Transport missing ListenThreadListener and TransportListener

Please Note: The variables are defined as object instances in the dedicated classes.

Is there a latest project that I perhaps missed out and downloaded the older version, maybe? I need to make use of the some of your components, but I need to understand first how the whole system works.
You may access the project from here:
https://github.com/darshanshah/VideoConferencingSystem/blob/master/VideoConferencingSystem/

Thanks in advance.

**Comment by kstan79** [comment]
spam
