### ISSUE TITLE
Error in pdf report (Frames objects)

### ISSUE THREAD

**Issue by onoboaits** [SIMITGROUP/phpjasperxml#68]
Hi, congratulations for your work, but i have this problem.

In my report when call the export in pdf, i get this error:

Fatal error: Uncaught Error: Call to undefined method PHPJasperXMLElement::element_frame() in C:\xampp\htdocs\hrmedic\reports\version\1.1\abstractPHPJasperXML.inc.php:952 Stack trace: #0 C:\xampp\htdocs\hrmedic\reports\version\1.1\PHPJasperXML.inc.php(111): abstractPHPJasperXML->default_handler(Object(SimpleXMLElement)) #1 C:\xampp\htdocs\hrmedic\reports\version\1.1\abstractPHPJasperXML.inc.php(789): PHPJasperXML->group_handler(Object(SimpleXMLElement)) #2 C:\xampp\htdocs\hrmedic\reports\version\1.1\abstractPHPJasperXML.inc.php(1340): abstractPHPJasperXML->xml_dismantle(Object(SimpleXMLElement)) #3 C:\xampp\htdocs\hrmedic\reports\version\1.1\abstractPHPJasperXML.inc.php(1346): abstractPHPJasperXML->load_xml_string('<?xml version="...') #4 C:\xampp\htdocs\hrmedic\reports\rptForm01.php(20): abstractPHPJasperXML->load_xml_file('rptform01.jrxml') #5 {main} thrown in C:\xampp\htdocs\hrmedic\reports\version\1.1\abstractPHPJasperXML.inc.php on line 952

My report xml in jasper report have some frames elements. 

The report in jpg is attached.
![form01_page1](https://user-images.githubusercontent.com/43496724/87721532-30fd4c00-c77c-11ea-8ef9-679d0f502c5c.JPG)
![form01_page2](https://user-images.githubusercontent.com/43496724/87721533-322e7900-c77c-11ea-861c-ee90e696b7a2.JPG)
![form01_page3](https://user-images.githubusercontent.com/43496724/87721534-322e7900-c77c-11ea-9f05-0f35a355a47f.JPG)

**Comment by fauzan1505** [comment]
Hi..
I have same problem..
can you solve this problem? please tell me..

thanks,

fau

**Comment by kstan79** [comment]
you shouldnt use frame or list, it is not supported
https://github.com/SIMITGROUP/phpjasperxml/wiki/Limitation

**Comment by kstan79** [comment]
since we use tcpdf, the result of textfield can be similar like here:
https://tcpdf.org/examples/example_006/

**Comment by onoboaits** [comment]
Hi, i fix the problem with no mount shapes, when the objects are mounted
the report has distortion.

Grettings

**Comment by fauzan1505** [comment]
> 
> 
> you shouldnt use frame or list, it is not supported
> https://github.com/SIMITGROUP/phpjasperxml/wiki/Limitation
> 
> usually i achieve similar result by put in html content into textfield

OK, Thanks for respond..
i was changed with rectangle..
