### ISSUE TITLE
ExportXLS.inc.php file missing 

### ISSUE THREAD

**Issue by nafeesahamed** [SIMITGROUP/phpjasperxml#69]
the source code is missing the files ExportXLS.inc.php

**Comment by kstan79** [comment]
it is parked inside 
phpjasperxml/version/1.0/
phpjasperxml/version/1.1/

**Comment by kstan79** [comment]
this repository closed, use new repository with new code base instead:
https://github.com/SIMITGROUP/phplibs

**Comment by kstan79** [comment]
sorry i decided to park latest code here again. you may try latest update using composer. it will help you auto install the dependency

**Comment by kstan79** [comment]
latest version auto pull excel lib via composer already, should not have this problem anymore.
