### ISSUE TITLE
Unable to diplay image blob in details

### ISSUE THREAD

**Issue by ricardoarbois1981** [SIMITGROUP/phpjasperxml#7]
Hi i need help in displaying image from mysql, i used the version 9e but it seems the image is not shown in the details section, i used ireport to design my report and all seems well in picture area,i check some documents online and none have resolve this issue, im using PHP 5.6 and im planning to use it on my upcoming project.I Hope someone can help as i'm a big fan of this software.Thanks

**Comment by kstan79** [comment]
hi, u can convert to base64 image instead. try this may help[https://stackoverflow.com/questions/16376734/encode-replace-blob-with-base64-in-php-array](url)

**Comment by ricardoarbois1981** [comment]
Thanks kstan79

      How can i apply  this in php and phpjasperxml, i know how to display image in base64, but i dont know how to apply it in the report, i tried some variation in jrxml, but no success, could you give me a piece of code that may apply in PHP that will apply also in jrxml since report usually execute by the PHP base from your product example. By the way im using a pure php to my project hope this helps.

**Comment by kstan79** [comment]
image u shall able to define image expression using $P{parameter} or $F{field1}. Use define base64 string into parameter of keep inside database, store in field1.

You can define as following expression too:
`"/var/www/storage/"+$P{imagename}`

**Comment by ricardoarbois1981** [comment]
Could you show me a proper coding in php and jrxml  this seems an error. thanks

$PHPJasperXML->arrayParameter=array("photo"=> base64_encode($photo))

I tried in with those example in jrxml:
1.) Original
<image>
<reportElement x="120" y="0" width="127" height="125" uuid="25e2fd53-645e-4063-81d5-26389f09d45d"/>
<imageExpression><![CDATA[$F{photo}]]></imageExpression>
</image>

2.) with parameter

<textField>
<reportElement x="289" y="31" width="100" height="20" uuid="46590839-c998-4d64-82f4-b8bd33b6eb2e"/>
<textFieldExpression><![CDATA[$P{paramphoto}]]></textFieldExpression>
</textField>

**Comment by ricardoarbois1981** [comment]
Just an update i modified my jrxml by adding the following.
<import value="org.apache.commons.codec.binary.Base64"></import>

<import value="org.apache.commons.codec.binary.Base64"></import>
new ByteArrayInputStream(Base64.decodeBase64($V{CSpaceLo
CSpaceLogo}.getBytes()))

Now i got this error. any idea?

 Class 'ByteArrayInputStream' not found in C:\xampp\htdocs\Jasper\class\PHPJasperXML.inc.php(5530)

**Comment by kstan79** [comment]
ByteArrayInputStream => java class. it is not supported.
beside, is this helpful?
[https://stackoverflow.com/questions/358500/base64-encode-in-mysql](https://stackoverflow.com/questions/358500/base64-encode-in-mysql)

**Comment by kstan79** [comment]
if above method string not helpful, u may hard code any base64 jpg/png string into image and try watch pdf render properly or not. due to this issue no received reply from you almost for few days i assume it solved.
