### ISSUE TITLE
Some Language not support

### ISSUE THREAD

**Issue by thameerakn** [SIMITGROUP/phpjasperxml#70]
Hi,

How can I add Specific font to the report. For example Thai Language. I add the font to the font location. But not sure how to pass the SetFont to the tcpdf.php. 

Kind Regards,
Thameera

**Comment by kstan79** [comment]
maybe here for you?

**Comment by kstan79** [comment]
this repository closed, use new repository with new code base instead:
https://github.com/SIMITGROUP/phplibs
