### ISSUE TITLE
Call to undefined function toUpperCase()

### ISSUE THREAD

**Issue by fauzan1505** [SIMITGROUP/phpjasperxml#71]
I use Expression in textfield :  $F{description}.toUpperCase()

I got error message "Call to undefined function toUpperCase(), Filename ... 1.1\abstractPHPJasperXML.inc.php(2396) : eval()'d code"

can you help me, please..

thanks,

fau

**Comment by fauzan1505** [comment]
my temporary solution : 

				   if (strpos($fm, '.toUpperCase()') !== false) {
 						$fm=substr($fm,0,strlen($fm)-strlen('.toUpperCase()'));
						$fm=strtoupper($fm);
 				   }

**Comment by kstan79** [comment]
touppercase is java syntax which is not supported. you shall use php way
https://github.com/SIMITGROUP/phpjasperxml/wiki/Do-something-beyond-standard-data-source

**Comment by kstan79** [comment]
no reply for sometimes, close case
