### ISSUE TITLE
Issue band group expression with ternary operator

### ISSUE THREAD

**Issue by fauzan1505** [SIMITGROUP/phpjasperxml#72]
Dear SIMITGROUP, 

I use ternary operator in expression band group example ($P{GROUP_BY}==1?$F{POLICY_NUMBER}:$F{LOCATION}) because i want to parse parameter group by sistem, and create variable total value (for calculate subtotal and total) with reset type is group  and reset group is group1,
with editor TIBCO Jaspersoft is no problem, it is mean view subtotal summary by group is OK, but with phpjasperxml subtotal NOT showing..

can you help me please?

thanks,

fau

**Comment by kstan79** [comment]
this repository closed, use new repository with new code base instead:
https://github.com/SIMITGROUP/phplibs

**Comment by kstan79** [comment]
you may install latest version and try it again, the latest version is using different kind of algorithm and maybe helpful
