### ISSUE TITLE
Fatal error: Uncaught Error: Attempt to assign property "sql" on null

### ISSUE THREAD

**Issue by MuhammadZakhy** [SIMITGROUP/phpjasperxml#73]
I'm using php 8.0.6 + MSSQL + jaspersoft
Here is my part of simple php code :

```
<?php
include_once("phpjasperxml-master/PHPJasperXML.inc.php");

$server = "localhost";
$user = "root";
$pass = "";
$db = "db_vmi";

$PHPJasperXML = new PHPJasperXML();
// $PHPJasperXML->debugsql=true;
// $PHPJasperXML->arrayParameter=array("parameter1"=>1);
$PHPJasperXML->load_xml_file("stok.jrxml");

$PHPJasperXML->transferDBtoArray($server,$user,$pass,$db);
$PHPJasperXML->outpage("I");    //page output method I:standard output  D:Download file
?>

```

Here is my query from jrxml file : 

![image](https://user-images.githubusercontent.com/86125988/128322406-0a17ccbc-081b-490c-b946-4e28f80a6c7f.png)

Here is the error that i've got : 

![image](https://user-images.githubusercontent.com/86125988/128321906-5348dc8c-e085-4731-942e-692a8121dd62.png)
![image](https://user-images.githubusercontent.com/86125988/128322035-dde01bfc-9517-440d-8611-a18d266f4b42.png)

Please help me to fix this kind of error
Thank you very much!

**Comment by kstan79** [comment]
this repository closed, use new repository with new code base instead:
https://github.com/SIMITGROUP/phplibs

**Comment by kstan79** [comment]
finally i decided to put latest code in this repository still, by right latest version support php7.4 and above (only), you may try it.

**Comment by kstan79** [comment]
not relavent to latest version anymore
