### ISSUE TITLE
Erro odbc

### ISSUE THREAD

**Issue by joaopaulozz** [SIMITGROUP/phpjasperxml#75]
Hello, 
I'm not able to connect via odbc, could you give me a light?

<?php
include_once("../PHPJasperXML.inc.php");

$link_logix = odbc_connect('xxxxx','xxx','xxxx');

$PHPJasperXML = new PHPJasperXML();
$PHPJasperXML->load_xml_file("sample1.jrxml");

$PHPJasperXML->transferDBtoArray($link_logix);
$PHPJasperXML->outpage("I");    //page output method I:standard output  D:Download file
?>

**Comment by kstan79** [comment]
syntax like this
$PHPJasperXML->transferDBtoArray(DBSERVER,DBUSER,DBPASS,DBNAME,$dbdriver);

**Comment by kstan79** [comment]
in latest version odbc is no longer supported, use pdo instead. refer https://github.com/SIMITGROUP/phpjasperxml/blob/master/examples/databasesample.php

**Comment by RomitKumar23** [comment]
Hello, 
I have a question, Can PHPJasperXML take image(blob) from database and print it in pdf?
Because I tried to do it but it's not working. So, I want if it's possible or my jrxml file has error.

**Comment by kstan79** [comment]
You may try convert the blob to base64 string before assign into the element
