### ISSUE TITLE
static/textField Rotate not woking

### ISSUE THREAD

**Issue by JoseMariadosSantosMachado** [SIMITGROUP/phpjasperxml#77]
`<staticText>
					<reportElement x="0" y="4" width="60" height="30" uuid="f5187bc6-d05d-481f-8617-724a031e316e">
						<property name="com.jaspersoft.studio.spreadsheet.connectionID" value="74ef20f6-ee01-45a5-9b79-11b2fb7b5edb"/>
						<property name="com.jaspersoft.studio.unit.height" value="px"/>
						<property name="com.jaspersoft.studio.unit.leftIndent" value="px"/>
					</reportElement>
					<textElement verticalAlignment="Middle" rotation="Left">
						<font isBold="true"/>
						<paragraph leftIndent="5"/>
					</textElement>
					<text><![CDATA[ID :]]></text>
				</staticText>`

**Comment by kstan79** [comment]
What you mean? Can give screenshoot?

**Comment by JoseMariadosSantosMachado** [comment]
[kstan79](https://github.com/kstan79)

> What you mean? Can give screenshoot?

![phpJasper](https://user-images.githubusercontent.com/97464402/167229629-2617b2b5-273e-4257-af88-ade753de2569.jpg)

**Comment by kstan79** [comment]
ya, rotation is not perfect due to upstream project cant handle it properly (tcpdf). We need to accommodate when we have at this moment. tcpdf going to come out new major upgrade but yet to release.

**Comment by kstan79** [comment]
no plan to improve it at the moment cause still rely on tcpdf.
