### ISSUE TITLE
No results thrown error

### ISSUE THREAD

**Issue by mattfreitas** [SIMITGROUP/phpjasperxml#78]
Hi, it's not documented where i should handle when the report has no data.. Currently this is the error: `No data found, and noData band undefined`
How should i handle that? I don't know if it's a bug or a lack of feature. Thanks.

**Comment by kstan79** [comment]
No data found usually sql execution cannot fetch row from server (mean 0 row), that's why it can't render the pdf. You may add nodata band if you wish to draw custom pdf content.

**Comment by williambh** [comment]
I must add 2 lines on my composer.json to fix a BUG and a missing 'case' key. 

1. `sed -i "s|password = \$config\['user'\]|password=\$config\['pass'\]|" vendor/simitgroup/phpjasperxml/src/datadrivers/Pdo_driver.php`
2. `sed -i "s|case 'java.lang.Long':|case 'java.lang.Long':\n\t\tcase 'java.lang.Integer':|" vendor/simitgroup/phpjasperxml/src/PHPJasperXML_load.php`

On first file, the class PDO_driver has a BUG! The array `$config` key `pass` it's missing! This was showing me the error "No data found, and noData band undefined". 
On second file, my report parameter type 'java.lang.Integer' was missing on `switch` that map parameter data type...

**Comment by kstan79** [comment]
i'd fix this bugs. thanks feed back!
