### ISSUE TITLE
simitsdk\phpjasperxml\PHPJasperXML::prop(): Argument #1 ($obj)

### ISSUE THREAD

**Issue by jvallejo17** [SIMITGROUP/phpjasperxml#79]
simitsdk\phpjasperxml\PHPJasperXML::prop(): Argument #1 ($obj) must be of type SimpleXMLElement, bool given, called 

require __DIR__."/../vendor/autoload.php";
use simitsdk\phpjasperxml\PHPJasperXML;
$filename = __DIR__.'/rptAlertas.jrxml';
$PHPJasperXML = new PHPJasperXML();
$PHPJasperXML->load_xml_file($filename);

phpversion 8.1.7

**Comment by kstan79** [comment]
hi, please supply more info. like the file content. seems like somethings wrong with load file.
