### ISSUE TITLE
Sample Code shows an error

### ISSUE THREAD

**Issue by tomermedina** [SIMITGROUP/phpjasperxml#8]
![image](https://user-images.githubusercontent.com/20295532/31060336-63f8c6ee-a744-11e7-806e-775b1b5565eb.png)
![image](https://user-images.githubusercontent.com/20295532/31060340-6d577ae6-a744-11e7-8ab3-0a8b614f599a.png)

**Comment by kstan79** [comment]
you may just off the warning by changing error_reporting & off the display_error

**Comment by tomermedina** [comment]
Found the error. Thanks
