### ISSUE TITLE
Attempt to assign property "sql" on null  after upgrade php to 8.18 from 7.4.14

### ISSUE THREAD

**Issue by lvsan** [SIMITGROUP/phpjasperxml#80]
Hi,
I am facing below error when try to open the reports which design using ireports 5.6  after i have upgrade my php version to 8.1.8.

 Error: Attempt to assign property "sql" on null in D:\wamp64\xxxxx\class\version\1.1\abstractPHPJasperXML.inc.php:55

in this case does the phpjasperxml stable version release as 1.1 will not able to be use anymore?
I will need to migrate the phpjasperxml version too?

Thanks.

regards,

Low

**Comment by kstan79** [comment]
you are encourage to use latest instead. cause php control getting tight and older version seems have many place not compatible with new php approach

**Comment by lvsan** [comment]
Hi Kstan79,

ok Noted. Will migrate it. However, how can I replace the old version to new version under yii2 framework for php?
Does the calling still the same?

Thanks.

Regards

Low

**Comment by kstan79** [comment]
No syntax changes, new version use name space and different code. Old version concept to far behind compare to recent programming approach.
