### ISSUE TITLE
RTL languge support And Persian(arabic) font support

### ISSUE THREAD

**Issue by moj101** [SIMITGROUP/phpjasperxml#81]
Hi
I designed a report for Persian language in Jasper Studio with Persian fonts, but unfortunately when I call with phpjasperxml  in my program with ???? Instead of letters I face. Is there a solution to this problem? Is it possible to add custom fonts to this program?
Sorry if the sentences are not clear because this text was prepared with Google translator

**Comment by kstan79** [comment]
Phpjasperxml using tcpdf class to generate pdf. If your font can't render properly you may generate TTF font in the tcpdf font library. Please refer tcpdf Document to know how to add more fonts

**Comment by moj101** [comment]
Thanks for the reply
Is it possible to post an example to do this?


> Phpjasperxml using tcpdf class to generate pdf. If your font can't render properly you may generate TTF font in the tcpdf font library. Please refer tcpdf Document to know how to add more fonts

Thanks for the reply
Is it possible to post an example to do this?

**Comment by kstan79** [comment]
https://queirozf.com/entries/adding-a-custom-font-to-tcpdf

This maybe helpful.
