### ISSUE TITLE
import is not supported, rendering stop 

### ISSUE THREAD

**Issue by lvsan** [SIMITGROUP/phpjasperxml#82]
HI,

I have migrate the phpjasperxml from version 1.1 to this new version.
Therefore, would like to check does the data under the config must have data?

I will need to recreate my ireport for this migration?

Below is the code that I have use and change for print the reports.

	 
$data=[];

$config = ['driver'=>'mysql',
		   'host'=>$server,
		   'user'=>$user,
		   'pass'=>$pass,
		   'name'=>$db,
		   'port'=>$port,
		   'data'=>$data];

$report = new PHPJasperXML();
$report->load_xml_file($reportName)    
    ->setDataSource($config)
    ->export('Pdf');

**Comment by kstan79** [comment]
yes if no data provided it will try to draw nodataband. you may try to use 'array' for testing:

```php


$config = [
    'driver'=>'array',
    'data'=>[ 
        ['user_id'=>0, 'fullname' => 'name1','email'=>'email1@a.com','gender'=>'M' ], 
        ['user_id'=>1, 'fullname' => 'name2','email'=>'email2@a.com','gender'=>'F' ], 
        ['user_id'=>2, 'fullname' => 'name3','email'=>'email3@a.com','gender'=>'M' ], 
        ]
];
```

refer [here](https://github.com/SIMITGROUP/phpjasperxml/blob/master/examples/databasesample.php) too:

**Comment by lvsan** [comment]
Hi kstan,

thanks for the advise. anyway i have try but still not working.

I have attach the files for your reference. hope someone can advise me.

thanks.

**Comment by lvsan** [comment]
Hi kstan,

thanks for the advise. anyway i have try but still not working.

Below is the code for my jrxml.

<?xml version="1.0" encoding="UTF-8"?>
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="purchasedelivery" language="groovy" pageWidth="595" pageHeight="842" columnWidth="588" leftMargin="6" rightMargin="1" topMargin="1" bottomMargin="1" isSummaryWithPageHeaderAndFooter="true" isFloatColumnFooter="true" whenResourceMissingType="Error" uuid="68cd62d6-e7be-4da6-819f-3a1a7ecac865">
	<property name="ireport.zoom" value="2.0"/>
	<property name="ireport.x" value="0"/>
	<property name="ireport.y" value="0"/>
	<import value="net.sf.jasperreports.engine.util.JRImageLoader"/>
	<queryString>
		<![CDATA[]]>
	</queryString>
	<field name="user_id" class="java.lang.String"/>
	<field name="fullname" class="java.lang.String"/>
	<field name="email" class="java.lang.String"/>
	<field name="gender" class="java.lang.String"/>
	<background>
		<band splitType="Stretch"/>
	</background>
	<pageHeader>
		<band height="160" splitType="Stretch">
			<staticText>
				<reportElement x="358" y="99" width="107" height="18" uuid="ab1fe004-536d-4d42-ae8f-1fe7244c414d"/>
				<textElement textAlignment="Right">
					<font size="9" isBold="true"/>
				</textElement>
				<text><![CDATA[PD No :]]></text>
			</staticText>
			<staticText>
				<reportElement x="358" y="116" width="107" height="18" uuid="223f13c1-f0e8-47f7-bb29-29d475089113"/>
				<textElement textAlignment="Right">
					<font size="9" isBold="true"/>
				</textElement>
				<text><![CDATA[Date :]]></text>
			</staticText>
			<staticText>
				<reportElement x="358" y="133" width="107" height="18" uuid="e8a2946d-005e-47de-b6ba-03b247609b51"/>
				<textElement textAlignment="Right">
					<font size="9" isBold="true"/>
				</textElement>
				<text><![CDATA[Credit Term :]]></text>
			</staticText>
			<staticText>
				<reportElement x="358" y="54" width="220" height="25" uuid="73f36593-9e83-474a-86f0-c000f0a81180"/>
				<textElement textAlignment="Center">
					<font size="13" isBold="true"/>
				</textElement>
				<text><![CDATA[PURCHASE DELIVERY ORDER]]></text>
			</staticText>
			<textField>
				<reportElement x="466" y="79" width="113" height="20" uuid="da703851-a267-4f2d-ac6a-45789c063bb1"/>
				<textElement>
					<font size="9"/>
				</textElement>
				<textFieldExpression><![CDATA[$V{PAGE_NUMBER}]]></textFieldExpression>
			</textField>
			<staticText>
				<reportElement x="358" y="79" width="107" height="20" uuid="3fa5b4f7-729a-4b0d-afb7-473800434ac3"/>
				<textElement textAlignment="Right">
					<font size="9" isBold="true"/>
				</textElement>
				<text><![CDATA[PAGE NO. :]]></text>
			</staticText>
		</band>
	</pageHeader>
	<columnHeader>
		<band splitType="Stretch"/>
	</columnHeader>
	<detail>
		<band height="75" splitType="Stretch">
			<staticText>
				<reportElement x="12" y="0" width="100" height="20" uuid="048e0b52-c108-40de-9de8-6539bc16c326"/>
				<text><![CDATA[user_id]]></text>
			</staticText>
			<textField>
				<reportElement x="123" y="0" width="100" height="20" uuid="1b3a2196-8bef-4225-a8f7-9001daabb772"/>
				<textFieldExpression><![CDATA[$F{user_id}]]></textFieldExpression>
			</textField>
			<staticText>
				<reportElement x="249" y="5" width="100" height="20" uuid="e96e6db1-3a37-4c0f-8e97-2adb8a8c143a"/>
				<text><![CDATA[fullname]]></text>
			</staticText>
			<textField>
				<reportElement x="349" y="5" width="100" height="20" uuid="a447285a-efa1-42c2-9810-c2f35ab539e2"/>
				<textFieldExpression><![CDATA[$F{fullname}]]></textFieldExpression>
			</textField>
			<staticText>
				<reportElement x="12" y="25" width="100" height="20" uuid="e2808279-b423-4456-bc56-88154ba508b2"/>
				<text><![CDATA[email]]></text>
			</staticText>
			<textField>
				<reportElement x="123" y="25" width="100" height="20" uuid="1e6ab91c-bfd7-41cb-90af-14d4fdfa368e"/>
				<textFieldExpression><![CDATA[$F{email}]]></textFieldExpression>
			</textField>
			<staticText>
				<reportElement x="252" y="33" width="100" height="20" uuid="36b57ac6-c9ce-4fd6-b959-2bec3b912b0b"/>
				<text><![CDATA[gender]]></text>
			</staticText>
			<textField>
				<reportElement x="352" y="33" width="100" height="20" uuid="3c7fd499-201d-441c-8c98-c777c7cd00ac"/>
				<textFieldExpression><![CDATA[$F{gender}]]></textFieldExpression>
			</textField>
		</band>
	</detail>
	<columnFooter>
		<band splitType="Stretch"/>
	</columnFooter>
	<pageFooter>
		<band height="34"/>
	</pageFooter>
	<summary>
		<band splitType="Stretch"/>
	</summary>
</jasperReport>



below is the php code


<?php

use simitsdk\phpjasperxml\PHPJasperXML;

$subDir =str_replace("/", addslashes("\\"), Yii::$app->basePath) . "\\reports\\";

$reportName = $_GET['report'];
$reportName = $subDir . $reportName . '.jrxml';

$data = [
        ['user_id'=>0, 'fullname' => 'name1','email'=>'email1@a.com','gender'=>'M' ], 
        ['user_id'=>1, 'fullname' => 'name2','email'=>'email2@a.com','gender'=>'F' ], 
        ['user_id'=>2, 'fullname' => 'name3','email'=>'email3@a.com','gender'=>'M' ], 
	];

$config = [
    'driver'=>'array',
	'data'=>$data
];

$report = new PHPJasperXML();
$report->load_xml_file($reportName)    
    ->setDataSource($config)
    ->export('Pdf'); 
	  
?> 


thanks.

**Comment by lvsan** [comment]
Hi,

i have remove the import value from the jrxml files. But when run, the report show me as below screen.

![image](https://user-images.githubusercontent.com/2595804/191204350-b6b56989-3f44-444e-8f1a-40bf06eefad9.png)

is there anyone know what this is meaning?

**Comment by lvsan** [comment]
Hi,

Have found there is error when using driver for mysql. 
check there is error under below:

 protected function connect(array $config)
    {
        $host = $config['host'];
        $user =  $config['user'];
        $pass =  $config['pass'];
        $name =  $config['name'];
        
        if(gettype($config['connection'])=='object')  //----- error here
        {
            $cn = $config['connection'];
        }
        else
        {
            $cn = new mysqli($host, $user, $pass, $name);
        }
        return $cn;
    }

so i modify the code from my site to 
        if(isset($config['connection']) && gettype($config['connection'])=='object')  

then it is working now. But does this is the issues that causing my reports not working?

I also need to connect the mysql with the portno which the port number is not default to be use from my site.

thanks.

**Comment by kstan79** [comment]
First of all, I would like to check with you is it the examples in the repository work in your computer? I worry you have php version issue.

Next, regarding the screenshoot displayed "%PDF-1.7...", usually this happen when there is some area at your framework accidentally printed some extra text cause the pdf pattern broken, the browser thought it is not valid pdf and display as plain text. 

regarding mysql connection issue, you tried define "server:port" in 1 variabled?

**Comment by lvsan** [comment]
Hi kstan,

I am using php version 8.1.18 + apache 2.4.54 _ mysql 8.0.21.
Does this version for the php is not compatible?


for the screenhot, i try to check any cannot found any yet. will continue to check.

regarding mysql connection issue, you tried define "server:port" in 1 variabled? i will try see either this can be work. 
this will be something like below :

'host'=>'localhost:3308',

$config = ['driver'=>'mysql',
		   'host'=>'localhost:3308',
		   'user'=>'root',
		   'pass'=>'',
		   'name'=>'testdb',
		   'data'=>$data];

**Comment by lvsan** [comment]
hi kstan,

i able to connect to my db with the recommend define "server:port" in 1 variable. 

thanks.

However, does is there anyway for me to visible the textfield from the reports? or i just amend from my site?
I try to load the image dynamically, is there any advise?

thanks.

**Comment by kstan79** [comment]
I not sure your problem, try change 
```php
$report->load_xml_file($reportName)    
    ->setDataSource($config)
    ->export('Pdf','some/writetable/folder/filename.pdf'); 
```
instead?

**Comment by lvsan** [comment]
Hi kstan,

is ok. I will check myself. Others issues is solve and the reports is running well. will need to fine tune something.

thanks.
