### ISSUE TITLE
Image from database store as blob not able to display

### ISSUE THREAD

**Issue by lvsan** [SIMITGROUP/phpjasperxml#83]
Hi,

I have try to display the image that is save under db with blob field type.

but the pdf never display the image. I debug the code, there is value have been display.

attachment is the value that is show when I console.

[img.txt](https://github.com/SIMITGROUP/phpjasperxml/files/9630786/img.txt)

the above never use the base_decode function yet.

Able to advise does the value return is correct? However, I have using path to display too, but nothing to be show too.

thanks..

**Comment by kstan79** [comment]
blob is not supported directly, you may refer https://github.com/SIMITGROUP/phpjasperxml/blob/master/src/PHPJasperXML_elements.php line 126

there is 2 alternative:
1. try change your expression from `$F{image}` to `base64_encode(${image})`, hope it working
2. add blob process in the code and send pull request. 

By the way, it is bad to keep images content in database, please stop this method. It increase your database management overhead, and hard to scale.

**Comment by lvsan** [comment]
Hi kstan,

Thanks. I know for that, currently will stop using the image contents. but now i am still facing the issues to display when i change it using path or filename.

attachment is the jrxml that i using for the reports.

[img.txt](https://github.com/SIMITGROUP/phpjasperxml/files/9631152/img.txt)

Does i need to identify the class for the image?

Possible advise me cause most of my customer will display the image for their invoice.

thanks.

**Comment by lvsan** [comment]
hi,

below is the imageExpression that i have:

array(8) { ["x"]=> string(1) "4" ["y"]=> string(1) "8" ["width"]=> string(2) "69" ["height"]=> string(2) "60" ["uuid"]=> string(36) "6e3e8e21-7c40-4064-96b9-41570f74704e" ["elementtype"]=> string(5) "image" ["imageExpression"]=> string(59) "D:\wamp64\www\xxxxxx\reports\companylogo.png" ["band"]=> string(8) "detail_0" }

**Comment by kstan79** [comment]
it seems like bugs, 
you try check https://github.com/SIMITGROUP/phpjasperxml/blob/master/src/Exports/Pdf_driver.php line 268-277.

You try put in your type according see it work? Pdf_driver extend from TCPDF class, the $this->drawtarget->Image() actually from upstream.

**Comment by lvsan** [comment]
Hi,

I have try but still the same. finally i able to display if i upload the image that is under jpeg format, png is not supported. 
Will check while does the png format is not supported.

Thanks.

**Comment by lvsan** [comment]
> 
I found the image have error as below:
GD library error: imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile

therefore cannot load. I will check what can I do for this error.

Thanks.

**Comment by lvsan** [comment]
Hi,

I manage to solve the issues and able to viewing the image now.
To solve this , i need to download the latest version for TCPDF V6.4.4  from https://github.com/tecnickcom/TCPDF

and then, under the filename "tcpdf.php" , amend the $img = imagecreatefrompng($file);  ==> $img = @imagecreatefrompng($file);

Thanks.

**Comment by kstan79** [comment]
Then you may fill report to tcpdf team for this fix. Cause nobody wish to change code which is manage by composer

**Comment by lvsan** [comment]
> GD library error: imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile

Yes. I have report this to the tcpdf team. thanks.
