### ISSUE TITLE
printWhenExpression not working fine

### ISSUE THREAD

**Issue by lvsan** [SIMITGROUP/phpjasperxml#84]
HI ,

I have set the printWhenExpression to false which i check the heigh of the brand already = 0 when under protected function drawBand.
But when i print the reports, the detail still display with height = 15.
I have debug and found out the height for the brandname still = 15 under 
$this->output->endBand($bandname); 

below is the code that still consider as original brand height when i debug.

 public function endBand(string $bandname)
    {
        $pageno = $this->PageNo();
        $columnno = $this->getColumnNo();
        if($this->pageOffSetY>0)
        {            
            // echo "<br/>end band  $bandname have pageOffSetY $this->pageOffSetY<br/>";
            $this->lastBandEndY =$this->pageOffSetY;
            $this->bands[$bandname]['endY'] = $this->pageOffSetY;
            $this->pageOffSetY=0;  
            
            $this->SetPage($this->getNumPages());
        }
        if(empty($this->pagecolumnoccupation[$pageno]))
        {
            $this->pagecolumnoccupation[$pageno] = [];
        }

        if(empty($this->pagecolumnoccupation[$pageno][$columnno]))
        {
            $this->pagecolumnoccupation[$pageno][$columnno]=[];
        }
	echo $bandname.'-'.$this->bands[$bandname]['height']."<br>";  --> i debug here using echo.
		
        $this->pagecolumnoccupation[$pageno][$columnno] = $this->lastBandEndY;
    }

can advise how can i set the height =0 for under this function?

thanks.

**Comment by kstan79** [comment]
seems u use multiple band, before I think too much, you use any of below?
1. multiple column
2. change the print vertical/horizontal

as far as I know, in basic condition it should support multiple detail band

**Comment by lvsan** [comment]
Hi,

I am not using multiple column and change the print for vertical/horizontal.

Yes, most of the time, i will using the multiple detail band. so far the multiple detail band is working, only the printWhenExpression will not working fine although it is already set the band height =0, but it is never reflected the value under  "public function endBand(string $bandname)" . When I echo the brand height under this function, the height still is original value.

thanks.

**Comment by lvsan** [comment]
Hi,

below is the result when i debug.

![image](https://user-images.githubusercontent.com/2595804/192412221-4fdd4ab2-15fe-4160-9ca2-d886133e1b0b.png)

The detail_1 should be 0 for band height  cause have set printWhenExpression and the value is false.

thanks.

**Comment by lvsan** [comment]
Hi,

Currently, i fix the band height when printWhenExpression is false wit swap the position for the code as below:

    protected function drawBand(string $bandname, mixed $callback=null)
    {		
        if($this->bands[$bandname]['height']==0)
        {
            return ;
        }

        if(isset($this->bands[$bandname]['printWhenExpression']))
        {
            $banddisplayexpression = $this->bands[$bandname]['printWhenExpression'];
            $isdisplay = $this->isDisplay($banddisplayexpression);
			
            if(!$isdisplay)
            {
                $height=0;
                $this->bands[$bandname]['height']=0;
            }
            else
            {
                $this->bands[$bandname]['height'] = $this->bands[$bandname]['originalheight'];
            }
        }
        $height = $this->bands[$bandname]['height'];
        if($height>0)
        {    
// move the below code from above  `if($this->bands[$bandname]['height']==0) `    
```
			$offsets = $this->output->prepareBand($bandname,$callback);
			 //$this->console($bandname);
			 //$this->console($offsets);
			$offsetx=(int)$offsets['x'];
			$offsety=(int)$offsets['y'];
```
	
			foreach($this->elements[$bandname] as $uuid =>$element)
            {
                $tmp = $element;
                $isdisplayelement = true;
                $framedisplay = true;
                if(isset($element['printWhenExpression']))
                {                   
                    $printWhenExpression = (string)$element['printWhenExpression'];
                    $isdisplayelement = $this->isDisplay($printWhenExpression);  					
                }
                $this->elements[$bandname][$uuid]['show']=$isdisplayelement;

                //if this element is within frame, depend on frame appear or not
                if(isset($this->elements[$bandname][$uuid]['frame']))
                {
                    $frameuuid =$this->elements[$bandname][$uuid]['frame'];
                    $isdisplayelement = $this->elements[$bandname][$frameuuid]['show']??true;
                }

                //only match printWhenExpression will draw element
                if($isdisplayelement && $framedisplay)
                {                    
                    $this->drawElement($uuid,$tmp,$offsetx,$offsety);
                }                            
            }
        }
        $this->output->endBand($bandname,$height);       
    }
 

Not sure does this is the correct way to solve it. 

Thanks.

**Comment by kstan79** [comment]
you may send pull request, and I will put aside at the moment. Cause i have no time to check due to this area may effect a lot, such as test multiple column, horizontal/vertical printing. Anyhow, glad you solve this problem.

**Comment by lvsan** [comment]
> you may send pull request, and I will put aside at the moment. Cause i have no time to check due to this area may effect a lot, such as test multiple column, horizontal/vertical printing. Anyhow, glad you solve this problem.

ok noted. I will try to pull.

thanks.
