### ISSUE TITLE
How do I get the PDF file in stream?

### ISSUE THREAD

**Issue by restodata2020** [SIMITGROUP/phpjasperxml#85]
Hello. I need to get the file streamed so I can save it later. Or how do I store it? I need your help, thank you.

**Comment by kstan79** [comment]
$report->load_xml_file($filename)    
    ->setDataSource($config)
    ->export('Pdf',"/path/to/filename.pdf");

**Comment by restodata2020** [comment]
Thank you, you helped me a lot.
