### ISSUE TITLE
SQL debug

### ISSUE THREAD

**Issue by malcolmfowler** [SIMITGROUP/phpjasperxml#87]
In the old version you could debug the SQL with
**$PHPJasperXML->debugsql=true;**

How do you do this in the latest version
I tried 
$report->load_xml_file("nrg_awb.jrxml")    
    **->debugsql(true)**    
    ->setDataSource($config)
    ->setParameter(['awbid'=>180573])
    ->export('Pdf') ; 

However this produces an error

**Comment by kstan79** [comment]
I aware this is important, but seems it is missing. sorry of inconvenient cause. i will leave it open till fixed.

**Comment by kstan79** [comment]
latest version supported debugsql, you may try
