### ISSUE TITLE
Error on Ubuntu 20 with PHP 7.4.33

### ISSUE THREAD

**Issue by malcolmfowler** [SIMITGROUP/phpjasperxml#88]
The following error occurs on my Ubuntu host running PHP 7.4.33 

Fatal error: Default value for parameters with a class type can only be NULL in /var/www/vhosts/nrggb.com/operations.nrggb.com/vendor/simitgroup/phpjasperxml/src/Tools/Toolbox.php on line 49

Any idea how to fix this?

**Comment by kstan79** [comment]
sorry, not aware this msg. this seems like some problem in jrxml, so far all have similar problem or only specific format?

**Comment by kstan79** [comment]
too long no response i assume problem solved. it tested in `php 8.2.12` no issue .
