### ISSUE TITLE
Error when print the jrxml report

### ISSUE THREAD

**Issue by lvsan** [SIMITGROUP/phpjasperxml#89]
Hi, 

I have try to print out the reports but the report display the below message to me. Does there is no support for , comma under the return eval($evalstr) ? 

"
Eval failed.

return 514 Chai Chee Lane #06-06 Bedok Industrial Estate,Singapore 469029;

syntax error, unexpected identifier "Chai", expecting ";"

"

Can advise does the data that is return have any issues? Previous version is working fine.

Thanks.

**Comment by kstan79** [comment]
hi. seems the data in the database can't evaluate using eval(). you may try to escape it if encounter "

**Comment by kstan79** [comment]
no feed back i assume issue solved
