### ISSUE TITLE
EVAL data have issues

### ISSUE THREAD

**Issue by lvsan** [SIMITGROUP/phpjasperxml#93]
Hi All,

When i try to print the report, and one of my item have the below data and will display me the error as below:

Eval failed.

return STRAW FOR WD3591, WD4268;

syntax error, unexpected token "for", expecting ";"

Can advise why this is happen, and what should I do? I try to remove it but still the same.

**Comment by kstan79** [comment]
your data is text or php script?
I couldn't imagine how your data eval yet. you may try to echo the eval before/after at file `src/PHPJasperXML_expression.php`, method `executeExpression()`.

**Comment by lvsan** [comment]
Hi Ks tan,

My data is from query and should be in textField format create at ireport.

However, I have add the condition below and working now.

                             if(str_contains($value,","))
                             {
                                           $value = '"'.$value.'"';
                             }

Under the method executeExpression().

Thanks.

Best regards,

Low Voon San
Assistant Project Manager
DCS Synthesis Pte Ltd

Office :  +65 6282 7655
Fax     :  +65 6742 7451
Email  : ***@***.******@***.***>
Corporate Video : www.synthesis.bz/video.html<http://www.synthesis.bz/video.html>
865 Mountbatten Road #05-27 Katong Shopping Centre Singapore 437844
***@***.***
***@***.***

**Comment by kstan79** [comment]
thanks, but i don't think it is reliable solution. 
the more proper solution is sit back and identify why your query doesn't evaluate as `string`, most probably your data type or etc reason.  Then apply better way.

At the mean time, you may separate maintain this file.

**Comment by lvsan** [comment]
Hi Ks tan,

Sure. However, only this data have this problem, but others data is ok.



Thanks.

Best regards,

Low Voon San
Assistant Project Manager
DCS Synthesis Pte Ltd

Office :  +65 6282 7655
Fax     :  +65 6742 7451
Email  : ***@***.******@***.***>
Corporate Video : www.synthesis.bz/video.html<http://www.synthesis.bz/video.html>
865 Mountbatten Road #05-27 Katong Shopping Centre Singapore 437844
***@***.***
***@***.***

**Comment by kstan79** [comment]
I did some improvements and by right it solve this issue. However still need sometime to test

**Comment by kstan79** [comment]
u may try latest, if same thing appear again reopen this issue
