### ISSUE TITLE
Need adbise for barcode label

### ISSUE THREAD

**Issue by lvsan** [SIMITGROUP/phpjasperxml#94]
HI All,

Can advise how can i get the barcode label in center or align the left? cause the design seem weird feedback from customer.

![image](https://github.com/SIMITGROUP/phpjasperxml/assets/2595804/3ab5c08c-b2a8-4e35-9dbf-3dcd8ed7f8bf)

below is the xml.

<?xml version="1.0" encoding="UTF-8"?>
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="barcode" language="groovy" pageWidth="135" pageHeight="145" columnWidth="135" leftMargin="0" rightMargin="0" topMargin="0" bottomMargin="0" whenResourceMissingType="Error" uuid="68cd62d6-e7be-4da6-819f-3a1a7ecac865">
	<property name="ireport.zoom" value="4.0"/>
	<property name="ireport.x" value="0"/>
	<property name="ireport.y" value="0"/>
	<parameter name="SUBREPORT_DIR" class="java.lang.String" isForPrompting="false">
		<defaultValueExpression><![CDATA[]]></defaultValueExpression>
	</parameter>
	<parameter name="x_axis" class="java.lang.Float" isForPrompting="false"/>
	<parameter name="y_axis" class="java.lang.Float" isForPrompting="false"/>
	<parameter name="leftmargin" class="java.lang.Float" isForPrompting="false"/>
	<parameter name="rightmargin" class="java.lang.Float" isForPrompting="false"/>
	<parameter name="barcodefield" class="java.lang.String" isForPrompting="false"/>
	<parameter name="barcodetype" class="java.lang.String" isForPrompting="false"/>
	<parameter name="prnF" class="java.lang.String"/>
	<parameter name="getUser" class="java.lang.String"/>
	<parameter name="getDate" class="java.lang.String"/>
	<queryString>
		<![CDATA[SELECT
     tempbarcode.`Item_Code` AS Item_Code,
     tempbarcode.`Item_Desc` AS Item_Desc,
     tempbarcode.`ItemBarcode` AS ItemBarcode,
     tempbarcode.Item_UsualPrice AS UPPPrice,
     tempbarcode.`Item_Price1` AS Item_Price1,
     tempbarcode.`RetailName` AS RetailName,
     tempbarcode.`Size_Desc` AS Size_Desc,
     tempbarcode.`Color_Desc` AS Color_Desc,
     tempbarcode.`Art_No` AS Art_No,
     tempbarcode.`RetailCode` AS RetailCode,
     tempbarcode.`Item_Price2` AS Item_Price2,
     tempbarcode.`PromoName` AS PromoName,
     tempbarcode.`PromoQty` AS PromoQty,
     tempbarcode.`PromoPrice` AS PromoPrice,
     tempbarcode.`Filter_1` AS Filter_1,
     tempbarcode.`Filter_2` AS Filter_2,
     tempbarcode.`Filter_3` AS Filter_3,
     tempbarcode.LabelType AS LabelType,
     tempbarcode.Item_Price3 AS Item_Price3
FROM
     `printbarcode` tempbarcode
WHERE Lastuser=$P{getUser} AND DATE_FORMAT(LastUpdate,'%Y-%m-%d')=$P{getDate}]]>
	</queryString>
	<field name="Item_Code" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="Item_Desc" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="ItemBarcode" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="Item_Price1" class="java.math.BigDecimal">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="RetailName" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="Size_Desc" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="Color_Desc" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="Art_No" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="RetailCode" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="Item_Price2" class="java.math.BigDecimal">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="Filter_1" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="Filter_2" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="Filter_3" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="LabelType" class="java.lang.String"/>
	<field name="PromoName" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="PromoQty" class="java.math.BigDecimal">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="PromoPrice" class="java.math.BigDecimal">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="UPPPrice" class="java.math.BigDecimal"/>
	<field name="Item_Price3" class="java.math.BigDecimal"/>
	<variable name="barcodeField" class="java.lang.String">
		<variableExpression><![CDATA[$F{ItemBarcode}]]></variableExpression>
	</variable>
	<variable name="UnitPrice" class="java.lang.String" resetType="Column">
		<variableExpression><![CDATA["S"+$F{Item_Price1}]]></variableExpression>
	</variable>
	<background>
		<band/>
	</background>
	<pageHeader>
		<band/>
	</pageHeader>
	<columnHeader>
		<band/>
	</columnHeader>
	<detail>
		<band height="145">
			<staticText>
				<reportElement mode="Opaque" x="33" y="119" width="35" height="22" forecolor="#FFFFFF" backcolor="#000000" uuid="ce182fdf-f497-4f63-9970-8ddb4149ddac">
					<printWhenExpression><![CDATA[$F{LabelType} == "F" && $F{PromoPrice}!=0 ? true : false]]></printWhenExpression>
				</reportElement>
				<textElement textAlignment="Center" verticalAlignment="Middle">
					<font fontName="Arial" size="14" isBold="true"/>
				</textElement>
				<text><![CDATA[FOR ]]></text>
			</staticText>
			<textField pattern="###0">
				<reportElement mode="Opaque" x="4" y="119" width="29" height="22" forecolor="#FFFFFF" backcolor="#000000" uuid="be29a0b5-ed7c-4bdb-9a34-b9f137943a34">
					<printWhenExpression><![CDATA[$F{LabelType} == "F" && $F{PromoPrice}!=0 ? true : false]]></printWhenExpression>
				</reportElement>
				<textElement textAlignment="Center" verticalAlignment="Middle">
					<font fontName="Arial" size="15" isBold="true"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{PromoQty}]]></textFieldExpression>
			</textField>
			<textField pattern="¤ #,##0.00">
				<reportElement mode="Opaque" x="68" y="119" width="65" height="22" forecolor="#FFFFFF" backcolor="#000000" uuid="9f7713de-86c5-47c6-b3cf-eb584265fbbf">
					<printWhenExpression><![CDATA[$F{LabelType} == "F" && $F{PromoPrice}!=0 ? true : false]]></printWhenExpression>
				</reportElement>
				<textElement textAlignment="Center" verticalAlignment="Middle">
					<font fontName="DejaVu Sans Mono" size="14" isBold="true"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{PromoPrice}]]></textFieldExpression>
			</textField>
			<textField pattern="¤ #,##0.00">
				<reportElement mode="Opaque" x="60" y="119" width="73" height="22" forecolor="#FFFFFF" backcolor="#000000" uuid="e9646a4a-9cca-4d9c-ab4f-9f4edd37dee3">
					<printWhenExpression><![CDATA[$F{LabelType} == "S" ? true : false]]></printWhenExpression>
				</reportElement>
				<textElement textAlignment="Center" verticalAlignment="Middle">
					<font fontName="DejaVu Sans Mono" size="14" isBold="true"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{Item_Price1}]]></textFieldExpression>
			</textField>
			<textField pattern="¤ #,##0.00">
				<reportElement x="7" y="117" width="126" height="24" uuid="ac5dd9be-5adb-4af7-9c3f-5396071117cd">
					<printWhenExpression><![CDATA[$F{LabelType} == "N" || $F{LabelType} == "" ? true : false]]></printWhenExpression>
				</reportElement>
				<textElement textAlignment="Center" verticalAlignment="Middle">
					<font fontName="DejaVu Sans Mono" size="17" isBold="true"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{Item_Price1}]]></textFieldExpression>
			</textField>
			<textField pattern="¤ #,##0.00">
				<reportElement mode="Opaque" x="54" y="119" width="79" height="22" forecolor="#FFFFFF" backcolor="#000000" uuid="906d4069-9a06-4a57-9c49-65180fe7934a">
					<printWhenExpression><![CDATA[$F{LabelType} == "P" ? true : false]]></printWhenExpression>
				</reportElement>
				<textElement textAlignment="Center" verticalAlignment="Middle">
					<font fontName="DejaVu Sans Mono" size="14" isBold="false"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{Item_Price1}]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement x="3" y="65" width="130" height="15" uuid="ebc0ed5b-5d33-4a9a-878e-928bb89a3b22"/>
				<textElement textAlignment="Center" verticalAlignment="Top">
					<font fontName="DejaVu Sans Mono" size="12"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{Item_Code}]]></textFieldExpression>
			</textField>
			<textField isStretchWithOverflow="true" isBlankWhenNull="true">
				<reportElement x="9" y="80" width="120" height="14" isRemoveLineWhenBlank="true" uuid="5e91a2d2-2f8c-4107-864b-4696f97956ae"/>
				<textElement textAlignment="Center">
					<font fontName="DejaVu Sans Mono" size="10" isBold="false"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{Item_Desc}]]></textFieldExpression>
			</textField>
			<staticText>
				<reportElement mode="Opaque" x="4" y="119" width="56" height="22" forecolor="#FFFFFF" backcolor="#000000" uuid="3de91c4b-3678-4c7d-be62-010eb49d99b0">
					<printWhenExpression><![CDATA[$F{LabelType} == "S" ? true : false]]></printWhenExpression>
				</reportElement>
				<textElement textAlignment="Right" verticalAlignment="Middle">
					<font fontName="Arial" size="14" isBold="true"/>
				</textElement>
				<text><![CDATA[OFFER]]></text>
			</staticText>
			<staticText>
				<reportElement mode="Opaque" x="4" y="119" width="50" height="22" forecolor="#FFFFFF" backcolor="#000000" uuid="868af93c-a0a0-4d06-add3-0abf4dd7b3bc">
					<printWhenExpression><![CDATA[$F{LabelType} == "P" ? true : false]]></printWhenExpression>
				</reportElement>
				<textElement textAlignment="Right" verticalAlignment="Middle">
					<font fontName="Arial" size="15" isBold="true"/>
				</textElement>
				<text><![CDATA[NETT]]></text>
			</staticText>
			<textField isBlankWhenNull="true">
				<reportElement mode="Opaque" x="4" y="119" width="129" height="22" forecolor="#FFFFFF" backcolor="#000000" uuid="8b87053a-8fc0-4ad4-a8dc-92117457e1b3">
					<printWhenExpression><![CDATA[$F{LabelType} == "F" && $F{PromoPrice}==0 ? true : false]]></printWhenExpression>
				</reportElement>
				<textElement textAlignment="Center" verticalAlignment="Middle">
					<font fontName="Arial" size="14" isBold="true"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{PromoName}]]></textFieldExpression>
			</textField>
			<textField pattern="¤ #,##0.00" isBlankWhenNull="true">
				<reportElement x="4" y="104" width="129" height="15" uuid="e9e2ab1e-5400-4b67-9654-c2eeb4fb7a39">
					<printWhenExpression><![CDATA[$F{Item_Price3}==0 ? false : true]]></printWhenExpression>
				</reportElement>
				<textElement textAlignment="Center" verticalAlignment="Middle">
					<font fontName="DejaVu Sans Mono" size="11"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{Item_Price3}]]></textFieldExpression>
			</textField>
			<textField pattern="¤ #,##0.00" isBlankWhenNull="true">
				<reportElement x="63" y="104" width="70" height="15" uuid="2ddc480a-8986-410f-8256-454ceb29c0b8">
					<printWhenExpression><![CDATA[($F{LabelType} == "F" && $F{PromoPrice} !=0) || $F{LabelType} == "S" ? true : false]]></printWhenExpression>
				</reportElement>
				<textElement verticalAlignment="Middle">
					<font fontName="DejaVu Sans Mono" size="11"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{UPPPrice}]]></textFieldExpression>
			</textField>
			<staticText>
				<reportElement x="4" y="104" width="47" height="15" uuid="767d37c8-19f0-4b22-8e01-61017e69bdfa">
					<printWhenExpression><![CDATA[($F{LabelType} == "F" && $F{PromoPrice} !=0) || $F{LabelType} == "S" ? true : false]]></printWhenExpression>
				</reportElement>
				<textElement textAlignment="Right" verticalAlignment="Bottom">
					<font fontName="Arial" size="11"/>
				</textElement>
				<text><![CDATA[U.P.]]></text>
			</staticText>
			<textField>
				<reportElement x="128" y="0" width="5" height="5" uuid="ce8580a4-713f-47cb-8d6b-99bb7dd6ca0b">
					<printWhenExpression><![CDATA[false]]></printWhenExpression>
				</reportElement>
				<textElement>
					<font fontName="Arial"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{LabelType}]]></textFieldExpression>
			</textField>
			<componentElement>
				<reportElement x="3" y="20" width="130" height="35" uuid="0f084c2d-d6e6-4cdc-8c14-dea173ea9170"/>
				<jr:barbecue xmlns:jr="http://jasperreports.sourceforge.net/jasperreports/components" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports/components http://jasperreports.sourceforge.net/xsd/components.xsd" type="EAN13" drawText="false" checksumRequired="false" barWidth="0" barHeight="44">
					<jr:codeExpression><![CDATA[$F{ItemBarcode}]]></jr:codeExpression>
				</jr:barbecue>
			</componentElement>
		</band>
	</detail>
	<columnFooter>
		<band/>
	</columnFooter>
	<pageFooter>
		<band/>
	</pageFooter>
	<summary>
		<band/>
	</summary>
</jasperReport>

**Comment by lvsan** [comment]
Hi Ks Tan,

Will you able to provide me the sample code on how does this to be change?


Thanks.

Best regards,

Low Voon San
Assistant Project Manager
DCS Synthesis Pte Ltd

Office :  +65 6282 7655
Fax     :  +65 6742 7451
Email  : ***@***.******@***.***>
Corporate Video : www.synthesis.bz/video.html<http://www.synthesis.bz/video.html>
865 Mountbatten Road #05-27 Katong Shopping Centre Singapore 437844
***@***.***
***@***.***

**Comment by kstan79** [comment]
No sample code, just align according pdf

**Comment by lvsan** [comment]
ok. let me try first. thanks.

**Comment by kstan79** [comment]
update latest 2.1.5, it has improve alignment

**Comment by lvsan** [comment]
thanks. will update and try now.

**Comment by lvsan** [comment]
executeExpression: $F{ItemBarcode}

after parse expressiom: <{{1005000255190}}>

string

executeExpression: "S"+$F{Item_Price1}

after parse expressiom: "S"+10.90

string

Eval failed.

return "S".10.90;

syntax error, unexpected floating-point number ".10", expecting ";"

when i try there is error while printing.

**Comment by kstan79** [comment]
You may temporary roll back last version, I notice some situation it happens and I need make some decision on source code

**Comment by lvsan** [comment]
noted for that. thanks.

**Comment by kstan79** [comment]
Try update latest
