### ISSUE TITLE
qrcode cannot print in more than one row in detail band

### ISSUE THREAD

**Issue by anggadedysaputro** [SIMITGROUP/phpjasperxml#96]
please help me....how to print qrcode in multiple rows?
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/fb7dba52-8eec-4420-ad56-8fde8f609cda)

the barcode not follow of rows

**Comment by kstan79** [comment]
Not understand, can give me screenshot of your design?

**Comment by anggadedysaputro** [comment]
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/f2011cb6-53eb-442a-8de5-b73ca7de84bc)
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/3e976412-77f3-4705-80d4-98493b1bde7c)

i run in jasper studio the output is normal,, when i run in php jasper(localhost) the qrcode pile up

**Comment by kstan79** [comment]
It look like bugs, you encounter similar issue when change to others barcode?

**Comment by anggadedysaputro** [comment]
yeah another barcode same issue,,
this is via localhost
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/a4106a86-2620-4bbc-8f2a-4b627797b3f4)

this is via jasper studio
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/8368ea65-df36-4857-8edb-8a0769445070)

Did I make a mistake in setting the jasper?

**Comment by kstan79** [comment]
u did fine, it is bug

**Comment by kstan79** [comment]
![sample](https://github.com/SIMITGROUP/phpjasperxml/assets/1889979/607ad04f-0e22-4be4-ade4-a4f3238e9e28)
update latest 2.1.5 for bug fix

**Comment by anggadedysaputro** [comment]
oh okey thank you so much,, i will try again
