### ISSUE TITLE
how to add padding in text ? test in jasper studio working but in localhost not working

### ISSUE THREAD

**Issue by anggadedysaputro** [SIMITGROUP/phpjasperxml#97]
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/95355e07-bec8-4209-8b04-565b41e8cf10)
in localhost
![gambar](https://github.com/SIMITGROUP/phpjasperxml/assets/13897032/c084266e-7382-49ab-99cd-9139a8aa56f9)
in jasper studio

**Comment by kstan79** [comment]
Yaya, it is not supported yet. Cause upstream project tcpdf needs extra effort.

**Comment by kstan79** [comment]
supprisingly i'd make it work. try latest v2.1.9

**Comment by anggadedysaputro** [comment]
thank you so much
